### ISSUE TITLE
"Semimajor" or "Semi-major"?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/keplers-laws#101]
For code review #83 ...

Is is "Semimajor" or "Semi-major"?   Both are used (see strings file below), and that's inconsistent.  I recommend "Semi-major", which is the correrct syntax for a compound adjective.

```
  "graph.a": {
    "value": "Semimajor Axis (a)"
  },
...
  "infoDialog.semimajorAxis": {
    "value": "<b>Semi-major axis (a):</b> represents half of the longest diameter of the elliptical orbit."
  },
  "infoDialog.semiminorAxis": {
    "value": "<b>Semi-minor axis (b):</b> represents half of the shortest diameter of the elliptical orbit."
  },
```

**Comment by pixelzoom** [comment]
This inconsistency also occurs throughout code names, e.g.

```ts
    public readonly semiMajorAxis: number,
```

```ts
      stroke: KeplersLawsColors.semimajorAxisColorProperty,
```

and code comments, e.g.

```ts
 * a: semi-major axis
```

```ts
// a is the semimajor axis
```

**Comment by pixelzoom** [comment]
There is still confusion about this.  And in strings.json:

```ts
  "infoDialog.semiMajorAxis": {
    "value": "<b>Semimajor axis (a):</b> represents half of the longest diameter of the elliptical orbit."
  },
  "infoDialog.semiMinorAxis": {
    "value": "<b>Semiminor axis (b):</b> represents half of the shortest diameter of the elliptical orbit."
  },
```

@AgustinVallejo will bring back to designers.  My recommendation is semi-major and semi-minor.

**Comment by arouinfar** [comment]
I prefer semi-major and semi-minor. I think they are more readable.

**Comment by kathy-phet** [comment]
I agree semi-major, semi-minor.

**Comment by DianaTavares** [comment]
agree

**Comment by pixelzoom** [comment]
OK, I will standardize on semi-major and semi-minor.   I believe the only remaining change are 2 values in strings.json.

**Comment by pixelzoom** [comment]
Done in the above commits. Screenshots below shows the strings in context.  

@AgustinVallejo please review, close if OK.

<img width="732" alt="screenshot_2754" src="https://github.com/phetsims/keplers-laws/assets/3046552/937da8a2-2a76-4197-b80a-b86a3b9f1645">

<img width="272" alt="screenshot_2756" src="https://github.com/phetsims/keplers-laws/assets/3046552/90b6eadf-3fad-497e-97aa-ddf3aad65649">
