### ISSUE TITLE
Dynamic locale problems with Info dialog

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/keplers-laws#102]
For code review #83 ...

With `?stringTest=dynamic`, the "Info" title on the Info dialog does not change.  And the dialog gets unnecessarily narrow, resulting in the icons scaling down, when only the Text node should scale down.  For example:

<img width="1119" alt="screenshot_2722" src="https://github.com/phetsims/keplers-laws/assets/3046552/94744518-f0d2-4dc2-b6b3-dce3ae469bf4">

**Comment by pixelzoom** [comment]
Here's the problem with the title - it's a hardcoded English string:

```ts
      title: new Text( 'Info', { font: new PhetFont( 32 ) } )
```

**Comment by AgustinVallejo** [comment]
Adding to the meta issue of Dynamic Layout: #122

**Comment by pixelzoom** [comment]
@AgustinVallejo and I worked on this. Resolved in the above commit.
