### ISSUE TITLE
Replace `bodies[0]` and `bodies[ 1 ]`

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/keplers-laws#107]
For code review #83 ...

`bodies[ 0 ]` appears 14 times in the code. This is apparently the sun. 

In EllipticalOrbitEngine, I see:

```ts
    this.sun = bodies[ 0 ];
```

So why not replace those `bodies[ 0 ]` occurrences with `sun`?

Or if some of these `bodies[ 0 ]` are not related to EllipticalOrbitEngine, then `sun = bodies[0]` should be defined where needed.

**Comment by pixelzoom** [comment]
I see the same problem with `bodies[ 1 ]`, which appears 6 times.

**Comment by AgustinVallejo** [comment]
Replaced with sun and planet
