### ISSUE TITLE
Difficult to find code based on names shown in the UI

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/keplers-laws#114]
For code review #83 ...

> - [ ] Does the organization and structure of the code make sense? Do the model and view contain types that you would expect (or guess!) by looking at the sim? Do the names of things correspond to the names that you see in the user interface?

I've had a relatively difficult time locating code base on what I see in the UI.  Based on the names of things that I see in the UI, I expected to find these classes, which do not exist:

- [x] TargetOrbitPanel
- [x] PeriodDivisionsPanel
- [x] SweptAreaAccordionBox
- [x] TVersusAGraphAccordionBox (or something similar)
- [x] StarMassPanel

The fact that the names don't correspond to what is displayed on the screen will be a big problem when this sim is instrumented for PhET-iO.  Highly recommended to change the names now, and factor out classes where possible to increase encapsulation.

**Comment by AgustinVallejo** [comment]
Renamed. For in-sim consistency, left the accordion boxes named as SecondLawGraphAccordionBox and ThirdLawGraphAccordionBox.

@pixelzoom Would you agree that naming works and would be easier to find? I think having them close together (i.e. FirstLawPanels, FirstLawGraphPanel...) really helped navigation whilst building the sim.

**Comment by pixelzoom** [comment]
👍🏻 sounds good.

**Comment by AgustinVallejo** [comment]
Thanks! Closing

**Comment by pixelzoom** [comment]
Reopening...

ThirdLawGraphAccordionBox is incorrectly named, it's not an accordion box:

```
export default class ThirdLawGraphAccordionBox extends Node {
```

`ThirdLawAccordionBox` is actually defined in ThirdLawPanels:

```ts
class ThirdLawAccordionBox extends AccordionBox {
```

If you're interested in consistency, I would:
(1) Give ThirdLawGraphAccordionBox a correct name
(2) Move ThirdLawAccordionBox to its own .ts file.

**Comment by pixelzoom** [comment]
FirstLawGraphPanel is incorrectly named. It's not a panel - it's an AlignBox:

```ts
FirstLawGraphPanel extends AlignBox
```

**Comment by pixelzoom** [comment]
I took care of renaming ThirdLawGraphAccordionBox => ThirdLawGraph, and FirstLawGraphPanel => FirstLawGraph.  @AgustinVallejo please review, then close if OK.
