### ISSUE TITLE
Model implementation lacks use of composition

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/keplers-laws#115]
For code review #83 ...

> - [ ]  Is composition favored over inheritance where appropriate? See https://en.wikipedia.org/wiki/Composition_over_inheritance.

KeplersLawModel extends SolarSystemCommonModel.  Both classes are very flat, with dozens of fields and methods. Unrelated aspects of the model are consequently all at the same level, with no separation or encapsualtion. This makes the implementation very overwhelming, and difficult digest.  

This could be addressed by using composition --  factoring out subcomponents that are responsibile for various encapsulated aspects of the model, and delegating to those subcomponents.  For example, instead of having this set of fields in SolarSystemCommonModel.ts, factor them out into a "time control" class.

```ts
  // Time control parameters
  public timeScale: number; // Scale of the model's dt
  public modelToViewTime: number; // Transform between model's and view's times
  public readonly timeProperty: NumberProperty;
  public readonly isPlayingProperty: BooleanProperty;
  public readonly timeSpeedProperty: EnumerationProperty<TimeSpeed>;
  public readonly hasPlayedProperty = new BooleanProperty( false );
```

This would be a huge change, and it's probably too late to attempt.  But keep this in mind for future code.

**Comment by AgustinVallejo** [comment]
Understood, thanks for the feedback. Will definitely keep in mind for the future.
Closing.
