### ISSUE TITLE
Address duplicate code

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/keplers-laws#117]
For code review #83 ...

> Are any significant chunks of code duplicated? In addition to manual identification, tools include: WebStorm Code > Analyze Code > Locate Duplicates and https://github.com/danielstjules/jsinspect.

Using WebStorm, I see significant chunks of duplication that have not been addressed, see below.  Other duplicates identified by WebStorm can be ignored.

- [x] EllipticalOrbitNode, 2 duplicates:
```ts
combineOptions<TextOptions>(
      {
        visibleProperty: new DerivedProperty(
          [
            model.stringsVisibleProperty,
            model.engine.eccentricityProperty
          ],
          ( visible, e ) => {
            return visible && ( e > 0 );
          }
        )
      }, KeplersLawsConstants.TEXT_OPTIONS, {
        scale: 1.5,
        stroke: KeplersLawsColors.distancesColorProperty,
        fill: KeplersLawsColors.distancesColorProperty
      } )
```

- [x] KeplersLawsTimeControlNode:
```ts
const trianglePath = new Path( new Shape().moveTo( 0, triangleHeight / 2 ).lineTo( -triangleWidth, 0 ).lineTo( 0, -triangleHeight / 2 ).close(), {
  fill: 'black'
} );
const trianglePath2 = new Path( new Shape().moveTo( 0, triangleHeight / 2 ).lineTo( -triangleWidth, 0 ).lineTo( 0, -triangleHeight / 2 ).close(), {
  fill: 'black'
} );
```

- [ ]  SecondLawGraph, 3 duplicates:
```ts
  protected override update(): void {
    const spacingBorders = this.getSpacingBorders();

    // Only update grid line sets which have less than 100 lines
    if ( spacingBorders.max - spacingBorders.min < 100 ) {
      super.update();
    }
  }
```

- [x] FirstLawCheckboxIcons, 2 duplicates:
```ts
      new Path( new Shape().circle( -focalDistance, 0, fociRadius ).circle( focalDistance, 0, fociRadius ), {
          fill: KeplersLawsConstants.FOCI_COLOR_OPTIONS.fill
        } )
```

- [ ] ThirdLawScreenIcon, KeplersLawsScreenIcon, FirstLawScreenIcon:
```ts
          new Path(
            new Shape().ellipse( 0, 0, semiMajorAxis, semiMinorAxis, 0 ),
            {
              stroke: SolarSystemCommonColors.orbitColorProperty,
              lineWidth: 1
            } ),
```

* FirstLawCheckboxIcons, 4 duplicates:
```ts
        new Path( new Shape().ellipse( 0, 0, semiMajorAxis, semiMinorAxis, 0 ), {
            stroke: SolarSystemCommonColors.foregroundProperty
          }
        ),
```

* ThirdLawScreenIcon, FirstLawScreenIcon:

```ts
          planet ?
          new ShadedSphereNode( 3, {
            mainColor: SolarSystemCommonColors.secondBodyColorProperty,
            x: semiMajorAxis
          } ) : new Node()
```

**Comment by AgustinVallejo** [comment]
Wondering how the SecondLawGraph fix would work. Since the three classes that override the update are each inheriting from three separate classes which inherit from Path. Their override uses self and super referencing, so I'm not sure how the best solution would be...

**Comment by pixelzoom** [comment]
I see what you're saying about the duplication in SecondLawGraph.  But it's not clear to me when there are > 100 ticks, or why you're handling this case in `update`.  Let's discuss.

**Comment by AgustinVallejo** [comment]
This graph is interesting because we dynamically update the ticks based on the orbital size. As the range of possible areas is huge, we create 7 sets of ticks, grids and labels, one for each power of ten in our range, as seen here:

https://github.com/phetsims/keplers-laws/blob/5e83576d028df46e26c3afedc904ffa0e738560b/js/common/view/SecondLawGraph.ts#L172-L178

Because of that, there are instances where simply updating the tick set would generate a huge amount of ticks (and grid lines and labels). So along with @samreid we implemented this solution, in which the set would only update if it detects there are fewer than 100 ticks to display.

**Comment by pixelzoom** [comment]
Reopening. @AgustinVallejo please review https://github.com/phetsims/keplers-laws/commit/981bd8af4241db65aceb695715b03aba805f8ec4, additional cleanup in SecondLawAccordionBox. Close if OK.

**Comment by pixelzoom** [comment]
@AgustinVallejo and I reviewed while pairing. Closing.
