### ISSUE TITLE
Documentation style could be improved

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/keplers-laws#118]
For code review #83 ...

Most of the documentation in this sim is fragments -- incomplete sentences, punctuation, etc.   Look at the header comment in just about any .ts file for examples.

I find this style to be distracting. I spend an inordinate amount of time trying to parse the comments.  It comes across as sloppy, and it's not a good look for public, open source code. I realize that you may be doing what you see in other PhET code -- because there's a lot of this style in PhET code. But I don't recommend imitiating that style.

So... It's a bit late in the process to go back and rewrite documentation. But I encourage you to adopt a better style for future code.

**Comment by AgustinVallejo** [comment]
Understood, will try to be more mindful in my documentation in the future. Thanks.
Closing.
