### ISSUE TITLE
Properly configure PeriodTimerNode to the Third Law Screen

### ISSUE THREAD

**Issue by AgustinVallejo** [phetsims/keplers-laws#12]
In the Third Law Screen, when you check Period (T) a stopwatch appears. Currently it doesn't do anything. It should play the Sim and pause after exactly one orbital period.

Any other design decisions around the stopwatch that I don't remember? @DianaTavares

**Comment by DianaTavares** [comment]
It is not a stopwatch, it is a period timer (like the one in Pendulum lab (lab screen)):
![image](https://user-images.githubusercontent.com/26031501/231243874-e1951967-1403-4101-93ac-4359d32ca876.png)

When the use click play, the color of the path changes from pink to blue, to let the user know when the measurement of the period starts.  The blue is the used in my solar system:
![image](https://user-images.githubusercontent.com/26031501/231244189-980707a4-7ae4-414b-87b6-9c66fa4fb4d9.png)

Probably the path (orbit) can do the same that pendulum does, once the period timer measures one round, the blue path dismisses its color to become pink again slowly.
![image](https://user-images.githubusercontent.com/26031501/231244945-d2ab9af0-76c4-4e4c-8441-763bd5a70eae.png)

**Comment by DianaTavares** [comment]
Today (May 11) Amy and í played with the simulation, and we identified these issues with the PeriodTimerNode:

- [ ] the readout of the period timer disappears after a couple of seconds after a measurement. The value needs to disappear only if the user uses it again, the user changes the orbit, closes the timer and activates it again.  
- [ ] The play button of the timer shouldn't be a play button of the simulation. If the body is not in movement, and the user clicks the play in the timer, it needs to stay in zero and the planet in its position until the user click in the play in the play panel. Check this behavior in the [Pendulum lab](https://phet.colorado.edu/sims/html/pendulum-lab/latest/pendulum-lab_en.html)
![Period Timer](https://github.com/phetsims/keplers-laws/assets/26031501/58515e03-3bb9-4589-b5d1-41d6694ac685)


- [ ] Also, the last gif shows how the period timer doesn't stop the movement of the objects. In Kepler, the planet need to continue moving after a revolution, while the blue line disappears slowly. 

- [ ] The position of the Period timer changes when the user interacts with the planet
![timer2](https://github.com/phetsims/keplers-laws/assets/26031501/461c2ade-7bca-453b-8a01-67b420bf1280)

- [ ] We have three ways to measure the period in the sim, and not all the time they get the same result. In this picture, I show how the T value in the graph is different from the year's readout and different for the Period result.
![image](https://github.com/phetsims/keplers-laws/assets/26031501/879fb9da-2735-47a2-b3bd-26ac8b2a7095)
