### ISSUE TITLE
Size panel of T vs a graph is different and looks strange

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/keplers-laws#121]
The size of the T vs A graph needs to have the same size all time, or it looks super strange when a user moves the mass slider. 
![bug](https://github.com/phetsims/keplers-laws/assets/26031501/f4230b25-3356-4c64-ac2c-a8918b1238a8)

**Comment by AgustinVallejo** [comment]
Same issue as https://github.com/phetsims/keplers-laws/issues/86, closing this one.
