### ISSUE TITLE
Kepler's Laws Sound Mixing

### ISSUE THREAD

**Issue by Ashton-Morris** [phetsims/keplers-laws#123]
Here are the first round of adjustments:

- Adjust the "metronome sound" down 20%
- Lower the "the body will crash in to the sun" sound by 5-10% your discretion
- Lower the "green success" sound down by 30%
- Lower the Period Divisions sound by 10%

Other notes: 

- When the reset button has been pressed it should not trigger the Period Divisions sound at the same time. If the Period Divisions are anything other than 4, it triggers the 4 sound to play on top of the reset sound.
- Currently the Star Mass slider is playing the Marimba and the orbit adjustment continuous sound while you slide it.

When those volume adjustments have been made I will take another listen!

**Comment by AgustinVallejo** [comment]
Regarding the last item, isn't that expected behavior? After all, changing the mass of the sun will affect size and eccentricity

**Comment by AgustinVallejo** [comment]
Also, I think the changes are ready, please revieiw again @Ashton-Morris

**Comment by Ashton-Morris** [comment]
I think it sounds good!

I am still getting this double sound though:

- When the reset button has been pressed it should not trigger the Period Divisions sound at the same time. If the Period Divisions are anything other than 4, it triggers the 4 sound to play on top of the reset sound.

**Comment by AgustinVallejo** [comment]
Fixed the double sound. Closing!
