### ISSUE TITLE
Improvements in the design of the graphs to have consistency

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/keplers-laws#124]
- [x] Eraser button 

We have two eraser buttons in the sim:
![image](https://github.com/phetsims/keplers-laws/assets/26031501/6b4433f1-32b2-4f60-a108-a3ef0dc18e58)

and
![image](https://github.com/phetsims/keplers-laws/assets/26031501/bd681e91-574f-4a9c-936d-b0eb1f77c99f)

They need to be in the same position. I like it more like it is on the third law screen,in the lower part to the left.

- [x] Top margin: the Swept Area graph panel needs the same top margin that the T vs a Graph

![image](https://github.com/phetsims/keplers-laws/assets/26031501/239a8b7b-6acc-456b-b5d3-1714ce34c45f)

- [x] Left margin, same problem, match with the T vs a Graph
![image](https://github.com/phetsims/keplers-laws/assets/26031501/b7505b45-ffb9-44cf-a56f-3afde8401ee1)

- [ ] Left alignment: text, buttons and other elements inside the graphs panels need to have the same alignment. In the case of left alignment, the `T` buttons have a correct alignment and distance to the edge of the panel. Then the erase button and little line of the T/a fraction need to move a little more to the right to match this left alignment. In the swept area, the graph can move to the left to have the same alignment that the other graph.

![image](https://github.com/phetsims/keplers-laws/assets/26031501/88a5d36f-3bfc-4984-b476-cf20d86e2fb2)

**Comment by DianaTavares** [comment]
- [ ] Button alignment: looks nice!! Except for the eraser button. When the button of the swept area changes position, verify that it has left and button alignment. 
![image](https://github.com/phetsims/keplers-laws/assets/26031501/b63085ce-569a-4ea3-9f62-d19738813b3c)

- [ ] Make the a vs T graph bigger: We can have a bigger a vs T graph to match the space in the panel that the fractions give. Try to make  `a` axis longer to match the right margin. If this means to also making T larger, we have space! Then just do it. 

![image](https://github.com/phetsims/keplers-laws/assets/26031501/9dc3539e-1cb8-477e-ad54-ac7a90099158)

**Comment by AgustinVallejo** [comment]
@DianaTavares Can you please give it another look? I think this is mostly solved.

**Comment by DianaTavares** [comment]
It looks amazing!!
