### ISSUE TITLE
Updates in the more Orbital Data option

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/keplers-laws#125]
During the interviews, teachers expressed a desire to have the numeric value of the angle between the vector v and r. Add that information and picture to the info button, need the next changes:

- [x] Split the readout pale into two. I also add colors to help to differentiate the data to correspond to each vector: 

![image](https://github.com/phetsims/keplers-laws/assets/26031501/3596cf5c-a47f-4094-982a-ccec89da0db9)

***Important Note*** This panel is always visible when "more orbital data is active”. Observe how │r│ also includes d1 in the readout. I hope this helps students to see the change in the r vector direction and magnitude when string is active. I think that the text d1 only appears when string is active. The other way, the readout only said │r│. 

- [x] Each panel needs its info button. For the case of the extra data, the panel looks like this:

![image](https://github.com/phetsims/keplers-laws/assets/26031501/8f1ad4ab-f18a-4644-9062-0e325889461e)

The picture of the r vector is correct, but the actual one of the v vector has a mistake, and you need the picture of the angle, then I add here the pictures needed. 

![InfoButtons_velocity_vector](https://github.com/phetsims/keplers-laws/assets/26031501/279cafe6-d85d-4150-8750-02d566949a3b)
![InfoButtons_theta_rv](https://github.com/phetsims/keplers-laws/assets/26031501/463c23cb-524b-4c87-b2ea-9c38203e5b53)

**Comment by AgustinVallejo** [comment]
Working on it! Also, it seems on your mockup the target orbit menu is in the middle of the controls. Is that an old mockup or should I also look into that change? Right now it's at the top of the controls

**Comment by AgustinVallejo** [comment]
Managed to make the initial split. Will continue later adding the colors.

**Comment by DianaTavares** [comment]
Oh yes, the right panel is an old version, ignore that part.
