### ISSUE TITLE
add another + zoom level 

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/keplers-laws#126]
With the target orbit, the suggested orbits are small, and hard to see the elements inside them. We need another + zoom level:

![image](https://github.com/phetsims/keplers-laws/assets/26031501/9ac15a34-8592-4a9c-b39f-51d492c6ed89)

**Comment by AgustinVallejo** [comment]
However, as seen in the screenshot, adding another zoom level will render the velocity arrow too big to fit on the screen when zoomed in. Is this something we want?

**Comment by DianaTavares** [comment]
Wow, that is true... but I really see in the interviews that they want to be able to see the elements of that orbits that are in the target option. I have three ideas:

- Can you play with the target orbits and see if in general the velocity vector can be smaller?
- Add a zoom vector slider, like the one in gravity force? 

Try first the zoom, and we analyze how useful is comparing bigger orbits vs not being able to access or full visualize the velocity.

**Comment by AgustinVallejo** [comment]
After playing around for a bit, I think two things:
- Making the vector smaller by default will make it almost impossible to control for bigger orbits, as they are very sensitive to small changes and if the arrow is per se small, it's really hard to match Juptier's orbit.
- Adding a zoom vector slider feels like a significant change in UI and UX, we should be very sure it's what we want.

I would advice against this change. Let me know @DianaTavares what do you think?

**Comment by AgustinVallejo** [comment]
Spoke with Diana on Slack and we agreed we wouldn't add another zoom level.
