### ISSUE TITLE
FirstLawMoreDataPanel on Second Law and Third Law screens

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/keplers-laws#137]
For code review #83 ...

Checking "More Orbital Data" in Preferences adds an additional panel to each screen.  In the First Law screen, it looks like this, where the added panel is the one at bottom left:

<img width="1115" alt="screenshot_2737" src="https://github.com/phetsims/keplers-laws/assets/3046552/19623997-ce04-4bde-b1cb-1683fe063175">

For the Second Law and Third Law screens, the layout looks wrong.  The additional panel appears to the left of the other panels, negatively impacting usability of the sim. See screenshots below.   Is this what you intended?

Is this panel even supposed to be visible for the Second Law and Third Law?  It's named FirstLawMoreDataPanel.  And I only see it created in FirstLawPanels.ts.

<img width="1120" alt="screenshot_2738" src="https://github.com/phetsims/keplers-laws/assets/3046552/90ab751a-d4e6-4b85-a6e0-6b55b23d0613">

<img width="1116" alt="screenshot_2739" src="https://github.com/phetsims/keplers-laws/assets/3046552/e360cb50-8905-40f2-9415-71b177e459a8">

**Comment by AgustinVallejo** [comment]
My bad! Fixed
