### ISSUE TITLE
Second Law: Turn panel into Accordeon Box

### ISSUE THREAD

**Issue by AgustinVallejo** [phetsims/keplers-laws#14]
Turn the Area Graph Panel into an accordeon box. Title will still be Swept Area and it will be closed by default. @DianaTavares can you confirm?

**Comment by samreid** [comment]
I'll work on this.

**Comment by samreid** [comment]
I converted it to an AccordionBox.  The default ellipse overlaps it, not sure if that's a new or pre-existing problem.  In any case, it looks like this now.  @AgustinVallejo can you please review?

<img width="1108" alt="image" src="https://user-images.githubusercontent.com/679486/231306598-cef32dfd-900f-4307-bf52-9bc1ce45e679.png">

**Comment by AgustinVallejo** [comment]
Looks good, thanks!
