### ISSUE TITLE
getAreaColor allocates colorPalette every time it's called.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/keplers-laws#145]
For code review #83 ...

In KeplersLawModel.ts:

```ts
public getAreaColor( area: OrbitalArea ): Color {
    const colorPalette = [
      '#FF92FF',
      '#FF6DFF',
      '#FF24FF',
      '#C800C8',
      '#A400A4',
      '#80007F'
    ];
```

This array is being allocated every time that `getAreaColor` is called. It should be promoted to `const COLOR_PALETTE` outside of the class definition.

**Comment by pixelzoom** [comment]
Or better yet, move the COLOR_PALETTE to KeplersLawsColors.ts.   And yes, it's OK to have colors in KeplersLawsColors.ts that are not instances of ProfileColorProperty.

**Comment by pixelzoom** [comment]
In the above commit, I moved the colors to KeplersLawsColors.ORBITAL_AREA_COLORS.  

@AgustinVallejo please review. Close if OK.

**Comment by AgustinVallejo** [comment]
Thanks! Looks like a nice fix, I was wondering myself if that could be done.
