### ISSUE TITLE
Inconsistent drag bounds across screens

### ISSUE THREAD

**Issue by AgustinVallejo** [phetsims/keplers-laws#147]
In the custom drag bounds for the planet designed by @jonathanolson, they act differently in the individual laws screens (fig1) vs the All Laws screen, which also contains the same panels (fig2):
![image](https://github.com/phetsims/keplers-laws/assets/37052186/f3099ea2-777a-4b27-90e3-77b2976a8998)
![image](https://github.com/phetsims/keplers-laws/assets/37052186/ce3e4313-e217-42cd-ae2b-b31ae9cdbaf8)

Would appreciate some help reviewing this regard.

**Comment by pixelzoom** [comment]
The visualization that we're seeing for the drag bounds is added in SolarSystemCommonScreenView:

```ts
    this.dragDebugPath = new Path( null, {
      stroke: 'red',
      fill: 'rgba(255,0,0,0.2)'
    } );
    if ( phet.chipper.queryParameters.dev ) {
      this.addChild( this.dragDebugPath );
    }
```

**Comment by AgustinVallejo** [comment]
Met with @jonathanolson and we found out the Laws Buttons were being created on all screens even though they were only used on the fourth. We conditioned the creation and this issue was fixed.
