### ISSUE TITLE
KeplersLawsControls panels should all have the same width

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/keplers-laws#148]
For #122...  

After maxWidth changes in #88, KeplersLawsControls.ts has a layout problem, see screenshot below.  We'd like all panels to have the same width, which they did before #88.  But the top panel is currently narrower.

<img width="375" alt="screenshot_2753" src="https://github.com/phetsims/keplers-laws/assets/3046552/bb606464-d0b0-459f-80bd-3cd1fafe9aa5">

**Comment by pixelzoom** [comment]
The layout problem was fixed in the above commits.  It was being caused by superflous/incorrect layout options to VBox. Note that this was another layout problem that was obfuscated by excessive nesting.
  
Also note the following class renames, for consistency and compatibility with (future) PhET-iO naming:
* KeplersLawsControls -> KeplersLawsPanels
* KeplersLawsOrbitalInformationBox -> OrbitalInformationPanel
* TargetOrbitsPanel -> TargetOrbitPanel
* TargetOrbitsComboBox -> TargetOrbitComboBox

@AgustinVallejo please review. Close if OK.

**Comment by AgustinVallejo** [comment]
Thanks for this!
