### ISSUE TITLE
Include d1 and d2 values in the values panel

### ISSUE THREAD

**Issue by AgustinVallejo** [phetsims/keplers-laws#15]

**Comment by AgustinVallejo** [comment]
I believe this needs further design decisions, as it was decided d1 and d2 should appear in the distances panel, but then I was told to remove them. So I think it's better to discuss this in a meeting. As well as the layout of the distances panel, which right now feels a little lackluster, maybe it would benefit from a little bit more descriptions.

**Comment by DianaTavares** [comment]
I don't think it is necessary to display the value of d1 and d2. The idea of them is to be a qualitative representation of a “string”. If users really want to be sure that adding them is always the same value, thy can take the measuring tape. 

But if the final decision is to add these values, I prefer them in the string readout:

![image](https://user-images.githubusercontent.com/26031501/232921460-1463488b-8126-4b5d-9293-f3c9dff4e57f.png)

**Comment by AgustinVallejo** [comment]
Today's design meeting: We agreed to leave the numbers out unless interviews show they are needed. Reason being that the conceptual representation is enough, adding numeric values can become overwhelming for the student. 

- [ ] Remove r, d1 and d2 values
- [ ] Remove whitespace in the top representation, it's causing it to show a wrong measurement of 2a.
