### ISSUE TITLE
Why is the "More Orbital Data" toggle in Preferences > Visual?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/keplers-laws#153]
The "More Orbital Data" toggle seems misplaced.  It is currently in the _Preferences > Visual_ tab:

<img width="776" alt="screenshot_2761" src="https://github.com/phetsims/keplers-laws/assets/3046552/95978992-e7f7-47e2-8c83-eab1197c1fa8">

The _Preferences > Visual_ tab is (as I understand it) for features related to the visual presentation of the UI -- like projector mode and interactive description. 

The "More Orbital Data" toggle is most definitely sim-specific. It adds an additonal panel to the First Law screen, the bottom panel in the screenshot below.  In other sims that have preferences for adding/removing UI components (Calculus Grapher, Geometric Optics, Acid-Base Solutions,...) such controls are in _Simulation > Preferences_.  So why is "More Orbital Data" in _Preferences > Visual_?

<img width="229" alt="screenshot_2760" src="https://github.com/phetsims/keplers-laws/assets/3046552/395dfde0-39d6-4129-acf1-c89a0a038ae0">

**Comment by AgustinVallejo** [comment]
You're right. I didn't know about simulation options. Closing.
