### ISSUE TITLE
Suggestions in the “more orbital data” panel 

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/keplers-laws#155]
- [x] When "strings is active" change the readout of `r` to:

![image](https://github.com/phetsims/keplers-laws/assets/26031501/dc1ed7d1-39be-40a1-992c-051fe21382b2)

- [x]  leave 90º always when “always circular” is checked 
![image](https://github.com/phetsims/keplers-laws/assets/26031501/cd672b84-ec9d-4ab9-86d5-316c24571b44)

**Comment by pixelzoom** [comment]
What if the "Always Circular" checkbox is checked?   In that case, shouldn't it be:

| r | = R = 2.00 AU

**Comment by DianaTavares** [comment]
yes! I like that!
