### ISSUE TITLE
Some controls/objects don't reset with Reset All

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/keplers-laws#159]
**Test device**
MacBook Air M1 chip

**Operating System**
13.5.1

**Browser**
Safari 16.6

**Problem description**
For https://github.com/phetsims/qa/issues/979, on all screens the checkbox for the stopwatch remains checked after pressing Reset All.

**Steps to reproduce**
1. On any screen, check the Stopwatch checkbox
2. Press Reset All

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Kepler's Laws‬
URL: https://phet-dev.colorado.edu/html/keplers-laws/1.1.0-dev.5/phet/keplers-laws_all_phet.html
Version: 1.1.0-dev.5 2023-09-07 23:32:34 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.6 Safari/605.1.15
Language: en-US
Window: 1317x706
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by Nancy-Salpepi** [comment]
Additional controls that don't reset:
- [ ] On the Second Law Screen: The Swept Area Accordion Panel will not reopen if closed
- [ ] On the Third Law Screen: The T vs A Graph Accordion Panel will not reopen if closed

**Comment by AgustinVallejo** [comment]
This should be fixed now. Let me know if there's anything else not resetting. Otherwise close if ready. Thanks @Nancy-Salpepi

**Comment by Nancy-Salpepi** [comment]
Everything looks fixed in main. I don't see anything else that isn't reseting, but will reopen if something comes up.

**Comment by Nancy-Salpepi** [comment]
Found another....the position of the Period Meter doesn't reset to its default position.

Steps:
1. On the Third Law Screen check the Period checkbox
2.  Move the Period Meter
3. Press Reset All
4. Check the Period checkbox

**Comment by Nancy-Salpepi** [comment]
and another....the bars in the Swept Area Graph don't reset with Reset All
<img width="914" alt="Screenshot 2023-09-11 at 3 38 42 PM" src="https://github.com/phetsims/keplers-laws/assets/87318828/697ef813-6f3c-4c50-94bc-d82f2b8caba6">

**Comment by AgustinVallejo** [comment]
The period timer thing was solved in https://github.com/phetsims/keplers-laws/issues/162

**Comment by AgustinVallejo** [comment]
The area bars thing was also solved in https://github.com/phetsims/keplers-laws/issues/165

Please review again and close if OK

**Comment by Nancy-Salpepi** [comment]
The period meter location now resets to its default location.

**Comment by AgustinVallejo** [comment]
@Nancy-Salpepi I think the last push finally fixed this and some other slight issues I was seeing with the areas filling up

**Comment by Nancy-Salpepi** [comment]
I no longer see that issue on main 🙂.
In the dev version and in main when I begin by using the step forward button instead of the play button, the filled areas don't disappear. Should I make a separate issue and close this one?

**Comment by AgustinVallejo** [comment]
I think this issue works well...

What you describe about the step forward button is a design oversight we never had discussed. So paging @DianaTavares: What should the area behavior be on step forward?
a. Deleting all the areas except the one the body is at. (If it's at half the area, draw that 50%)
b. Not deleting the areas

**Comment by AgustinVallejo** [comment]
After speaking with @DianaTavares on Slack, we're leaving the step button as it is and actually changing the Play button behavior so it doesn't delete areas.

**Comment by AgustinVallejo** [comment]
@Nancy-Salpepi forgot to mention. That would be it for this issue. As always, please close if OK or reopen if you encounter problems with the reset all (although QA is over so I'm not sure if more testing will ensue)

**Comment by Nancy-Salpepi** [comment]
This new change is working nicely on main. We can finally close this issue!!!!!!!!!!!!!!
