### ISSUE TITLE
Pressing Play button on Period Meter unpauses sim

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/keplers-laws#161]
**Test device**
MacBook Air M1 chip

**Operating System**
13.5.1

**Browser**
Safari 16.6

**Problem description**
For https://github.com/phetsims/qa/issues/979, on the Third Law and All Laws Screens, pressing play on the Period Meter unpauses the sim. 

**Steps to reproduce**
1. On the Third Law Screen, check the Period Meter Checkbox
2. Press Play on the Period Meter 

**Visuals**

https://github.com/phetsims/keplers-laws/assets/87318828/ab86d54b-0c1c-43a4-a5a5-867d95acf3c1

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Kepler's Laws‬
URL: https://phet-dev.colorado.edu/html/keplers-laws/1.1.0-dev.5/phet/keplers-laws_all_phet.html?stringTest=dynamic
Version: 1.1.0-dev.5 2023-09-07 23:32:34 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.6 Safari/605.1.15
Language: en-US
Window: 1435x706
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by AgustinVallejo** [comment]
My bad, closed accidentally. Please review @Nancy-Salpepi and close if OK.

**Comment by Nancy-Salpepi** [comment]
This looks good on main 🙂. Closing.
