### ISSUE TITLE
Period meter moves when I zoom in/out

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/keplers-laws#162]
**Test device**
MacBook Air M1 chip

**Operating System**
13.5.1

**Browser**
Safari 16.6

**Problem description**

For https://github.com/phetsims/qa/issues/979, on the Third Law screen, if I press the zoom in/out buttons the period meter moves (and can even move off screen).  I expected the behavior of the period meter to be the same as the stopwatch, which doesn't move at all. 

**Steps to reproduce**

1. On the Third Law screen, press the zoom in button
2. Check the Period checkbox--move it higher on the screen
3. Press the Zoom In button. 

**Visuals**

https://github.com/phetsims/keplers-laws/assets/87318828/399a5487-514f-41b3-a76a-3009ff8d7edc

**Comment by AgustinVallejo** [comment]
Should be fixed now

**Comment by Nancy-Salpepi** [comment]
This looks good now on main. Closing.
