### ISSUE TITLE
Period division marks disappear when number of divisions is changed.

### ISSUE THREAD

**Issue by AgustinVallejo** [phetsims/keplers-laws#165]

**Comment by KatieWoe** [comment]
I noticed this issue as well in https://github.com/phetsims/qa/issues/979.

**Comment by AgustinVallejo** [comment]
This also involves the fact that the number display suddenly appear like this when switching period divisions... Still investigating 
![image](https://github.com/phetsims/keplers-laws/assets/37052186/982c1c15-feb2-4e72-abcb-824b418c6bad)

**Comment by AgustinVallejo** [comment]
Fixed. Closing.
