### ISSUE TITLE
Arrow in graph on Third Law screen in buggy

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/keplers-laws#166]
**Test device**
MacBook Air M1 chip and Dell 

**Operating System**
macOS 13.5.1 and Win10

**Browser**
Safari and chrome

**Problem description**
For https://github.com/phetsims/qa/issues/979, I'm seeing 2 odd things with the arrow in the graph on the Third Law screen:
-It can end up alongside the graph line instead of at the end of it. 
-If I press Eraser button, the arrow will stay on the screen 

**Steps to reproduce**
1. On the third law screen move the body QUICKLY to the right --you will see the arrow appear at the end of the line and then move to the center of the graph area. 
2. Press the eraser button--line disappears but the arrow stays. 

**Visuals**

https://github.com/phetsims/keplers-laws/assets/87318828/b60b2096-4360-4466-ae18-8fa698c74af8

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Kepler's Laws‬
URL: https://phet-dev.colorado.edu/html/keplers-laws/1.1.0-dev.5/phet/keplers-laws_all_phet.html
Version: 1.1.0-dev.5 2023-09-07 23:32:34 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36
Language: en-US
Window: 1332x724
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by AgustinVallejo** [comment]
The second item is intended. If you erase the graph but the body is still outside the graph, the arrow should pop up in the middle indicating the body is out of bounds, this is to avoid a blank empty graph.

The other comments could get some improvements, will take a look.

**Comment by AgustinVallejo** [comment]
Should be ready to review, please close if OK. Thanks!

**Comment by Nancy-Salpepi** [comment]
Looks good on main. Closing.
