### ISSUE TITLE
Area and time values off before scene plays.

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/keplers-laws#167]
**Test device**
Samsung
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/979
Related to reset all issues. When you reset the second screen and look at the area and time values, especially if you change the orbit, one of the sections may say zero area and time, even on the other side of the orbit from the planet. This is while paused before the scene is played.

**Visuals**
![changegraph](https://github.com/phetsims/keplers-laws/assets/41024075/b036b6b2-307d-40d2-ac99-6255a833b4a3)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Kepler's Laws‬
URL: https://phet-dev.colorado.edu/html/keplers-laws/1.1.0-dev.5/phet/keplers-laws_all_phet.html
Version: 1.1.0-dev.5 2023-09-07 23:32:34 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36
Language: en-US
Window: 1536x707
Pixel Ratio: 1.25/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 4096
Texture: size: 8192 imageUnits: 32 (vertex: 32, combined: 64)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by AgustinVallejo** [comment]
I believe this was also fixed with https://github.com/phetsims/keplers-laws/issues/159 can you check on phet-test and close if OK?

**Comment by KatieWoe** [comment]
Looks ok on main after a quick check
