### ISSUE TITLE
CT: multiple errors with "fuzz : unbuilt : listenerOrderRandom" test

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/keplers-laws#170]
```
keplers-laws : fuzz : unbuilt : listenerOrderRandom
http://128.138.93.172/continuous-testing/ct-snapshots/1695133077633/keplers-laws/keplers-laws_en.html?continuousTest=%7B%22test%22%3A%5B%22keplers-laws%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22listenerOrderRandom%22%5D%2C%22snapshotName%22%3A%22snapshot-1695133077633%22%2C%22timestamp%22%3A1695134469839%7D&brand=phet&ea&fuzz&listenerOrder=random
Query: brand=phet&ea&fuzz&listenerOrder=random
Uncaught Error: Assertion failed: max > min required for moduloBetween
Error: Assertion failed: max > min required for moduloBetween
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1695133077633/assert/js/assert.js:28:13)
at assert (Utils.js:58:14)
at moduloBetweenDown (EllipticalOrbitEngine.ts:399:29)
at Array.forEach
at forEach (EllipticalOrbitEngine.ts:390:22)
at calculateOrbitalDivisions (EllipticalOrbitEngine.ts:579:9)
at resetOrbitalAreas (EllipticalOrbitEngine.ts:187:13)
at callback (Multilink.ts:111:10)
at listener (TinyEmitter.ts:123:8)
at emit (ReadOnlyProperty.ts:315:22)
[URL] http://128.138.93.172/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1695133077633%2Fkeplers-laws%2Fkeplers-laws_en.html&simQueryParameters=brand%3Dphet%26ea%26fuzz%26listenerOrder%3Drandom&testInfo=%7B%22test%22%3A%5B%22keplers-laws%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22listenerOrderRandom%22%5D%2C%22snapshotName%22%3A%22snapshot-1695133077633%22%2C%22timestamp%22%3A1695134469839%7D
```

**Comment by pixelzoom** [comment]
Also occurring with the "fuzz : unbuilt : listenerOrderRandom" test:

```
keplers-laws : fuzz : unbuilt : listenerOrderRandom
http://128.138.93.172/continuous-testing/ct-snapshots/1695140008322/keplers-laws/keplers-laws_en.html?continuousTest=%7B%22test%22%3A%5B%22keplers-laws%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22listenerOrderRandom%22%5D%2C%22snapshotName%22%3A%22snapshot-1695140008322%22%2C%22timestamp%22%3A1695140295112%7D&brand=phet&ea&fuzz&listenerOrder=random
Query: brand=phet&ea&fuzz&listenerOrder=random
Uncaught Error: Assertion failed
Error: Assertion failed
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1695140008322/assert/js/assert.js:28:13)
at assert (SoundClip.ts:276:14)
at setPlaybackRate (OrbitalSound.ts:42:28)
at callback (Multilink.ts:111:10)
at listener (TinyEmitter.ts:123:8)
at emit (ReadOnlyProperty.ts:315:22)
at _notifyListeners (ReadOnlyProperty.ts:262:13)
at unguardedSet (ReadOnlyProperty.ts:246:11)
at set (Property.ts:54:10)
at (EllipticalOrbitEngine.ts:310:36)
[URL] http://128.138.93.172/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1695140008322%2Fkeplers-laws%2Fkeplers-laws_en.html&simQueryParameters=brand%3Dphet%26ea%26fuzz%26listenerOrder%3Drandom&testInfo=%7B%22test%22%3A%5B%22keplers-laws%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22listenerOrderRandom%22%5D%2C%22snapshotName%22%3A%22snapshot-
```

**Comment by pixelzoom** [comment]
In Slack#DM, @AgustinVallejo asked me:
> Went to replicate the listenerOrder=random one, and the console seems all red, full of reentries and invalid values... How worried should I be? Not sure if I should try to correct them? Only the one in the issue? Why is the one in the issue reported but the rest of them not?

The errors hit by `listenerOrder=random` will depend on what is being exercised in the sim.  So you’ll see different errors depending on what fuzzing interacts with.  How worried should I be?… This type of order means that you have ordering dependencies in you code, which is generally to be avoided.  The way to avoid this is to test with `listenerOrder=random` throughout development. If you wait until code review (or later in this case) then these are difficult problems to solve.

At this point in the process, it’s up to you whether you want to tackle them now, or defer for future.  If you defer, the issue should remain open, because it will continue to be reported by CT.

**Comment by samreid** [comment]
We were able to reproduce this with ?listenerOrder=reverse&fuzz, and we saw that semiMajorAxisProperty was coming out negative.

**Comment by marlitas** [comment]
This was being caused by the `massProperty.reset()` in `Body.ts`. I played around to see if there was another easy way to avoid the mixup during reset, but the reset is used to properly calculate the values for a Body when it becomes active, so these values do indeed need to be recalculated at that time and cannot be skipped over. `hasListenerOrderDependencies: true` fixed the problem and feels appropriate for this scenario.

**Comment by marlitas** [comment]
Will keep an eye on CT for the rest of the day, but this error was easy to replicate so I feel confident this is solved.

**Comment by marlitas** [comment]
This looks clear on CT. Ready for code review. Over to @AgustinVallejo

**Comment by pixelzoom** [comment]
I only see a commit on the main branch.  Does this need to be cherry picked to the 1.1 branch?  Kepler's is in the middle of RC testing.

**Comment by marlitas** [comment]
That's up to @AgustinVallejo. I made the fix on main to cleanup CT.

**Comment by AgustinVallejo** [comment]
Thanks @marlitas. I think we can cherry pick this issue. Marking as such.

**Comment by KatieWoe** [comment]
I didn't see any problems in the spot check when fuzzing on the debug version. If there is another way to test this, let me know.

**Comment by AgustinVallejo** [comment]
Nope, not that I know of. Should I close then?

**Comment by KatieWoe** [comment]
If there's nothing else for us to look out for, sure.
