### ISSUE TITLE
Period Timer resets position when finished timing

### ISSUE THREAD

**Issue by AgustinVallejo** [phetsims/keplers-laws#172]
Noticed during https://github.com/phetsims/qa/issues/984, should be straightforward, will fix in a moment.

**Comment by Nancy-Salpepi** [comment]
It also returns to the default position if I press the Rewind button.

**Comment by Nancy-Salpepi** [comment]
Agustin--I still see that the period timer resets to the default position if I press the rewind button.

**Comment by AgustinVallejo** [comment]
Might be phet-test, I'm up to date in main and it seems fixed.

**Comment by Nancy-Salpepi** [comment]
hmmmmm I cleared my cache multiple times and pulled all multiple times and I still see this:

https://github.com/phetsims/keplers-laws/assets/87318828/2f32e83b-075d-46ad-b70e-e3e9492f7f54

**Comment by Nancy-Salpepi** [comment]
I see what you originally reported is fixed. It is the part that I added that still seems broken.

**Comment by AgustinVallejo** [comment]
You are right, I wasn't looking at the sim's restart button. Understood the stopwatch restart one. Should be fixed now. Thanks @Nancy-Salpepi

**Comment by Nancy-Salpepi** [comment]
This looks fixed now. 
Keeping open to verify in the next rc. 
@AgustinVallejo should I change label to Status: fixed awaiting deploy?

**Comment by Nancy-Salpepi** [comment]
This looks fixed in rc.2.
Closing!
