### ISSUE TITLE
Graph doesn't always reset 

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/keplers-laws#173]
**Test device**
MacBook Air M1 chip

**Operating System**
13.5.2

**Browser**
Safari 16.6

**Problem description**
For https://github.com/phetsims/qa/issues/984, on the Third Law Screen, if the Always Circular checkbox is checked, you have to press Reset All twice to clear the graph.

**Steps to reproduce**
1. On the Third Law Screen, check Always Circular checkbox
2. Press Reset All

**Visuals**

https://github.com/phetsims/keplers-laws/assets/87318828/077f1e52-2897-4177-aa59-8c0776c4d71b

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Kepler's Laws‬
URL: https://phet-dev.colorado.edu/html/keplers-laws/1.1.0-rc.1/phet/keplers-laws_all_phet.html
Version: 1.1.0-rc.1 2023-09-18 17:02:56 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.6 Safari/605.1.15
Language: en-US
Window: 1430x710
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by AgustinVallejo** [comment]
Changed a bit the logic. Now this issue should be solved, and included an erase of the graph when Always Circular is toggled on. Please review and close if ready, @Nancy-Salpepi, thanks!

**Comment by Nancy-Salpepi** [comment]
This looks fixed on main and the erase of the graph occurs when Always Circular is toggled on. @AgustinVallejo we should keep this open to be verified in the next rc.

**Comment by Nancy-Salpepi** [comment]
Looks good in rc.2!
Closing.
