### ISSUE TITLE
Period Timer and Stopwatch are missing interactive highlights

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/keplers-laws#174]
**Test device**
MacBook Air M1 chip

**Operating System**
13.5.2

**Browser**
Safari 16.6

**Problem description**
For https://github.com/phetsims/qa/issues/984, the buttons on the period timer and stopwatch have interactive highlights but the entire period timer doesn't have a highlight for mouse or alt input. The stopwatch doesn't have an interactive highlight for alt input.

**Comment by AgustinVallejo** [comment]
@DianaTavares @arouinfar do you think this blocks publication? Spoke with @jessegreenberg and he mentioned it is a scenery-phet issue, at least the Stopwatch node part of it. (https://github.com/phetsims/scenery-phet/issues/820)

**Comment by AgustinVallejo** [comment]
![image](https://github.com/phetsims/keplers-laws/assets/37052186/4c2bfcdc-24f7-4575-8c9b-01c08367807c)
Added interactive highligts and alt input to period timer node. However, we have a question: When focusing the button is it okay that the arrow keys still can move the period timer? @jessegreenberg said it seems reasonable but want to know what's the opinion of QA and designers. @Nancy-Salpepi @DianaTavares @arouinfar

**Comment by DianaTavares** [comment]
For me, looks strange that you can move the Period timer node when the element selected is the play. That doesn't happen with the stopwatch, then as well for consistency, the period timer should move only when the full object is selected. That is what I think just because looks strange, and it is inconsistent, but I am not an expert in accessibility to take the last desition.

**Comment by AgustinVallejo** [comment]
On today's standup, we decided that the correct functionality is the one in the Period Timer. Designers expressed that the Stopwatch didn't block publication but that if it could be done for this version, they would very much like that. @jessegreenberg and I will implement it.

**Comment by arouinfar** [comment]
The behavior of the Period Timer on main seems reasonable to me (focus first on the tool body, then focus on the button). Focusing on the entire body cues that the tool is a movable object.  I think it's okay (and perhaps more convenient) for the tool to remain movable with the arrow keys when the focus shifts to the button.

**Comment by DianaTavares** [comment]
Yes, it is convenient that the tools can move when the focus is on the buttons, but my worry is that it is not evident for the user to know that move it is possible. I wonder if it is possible to have a second focus, or other ideas that we discuss in the meeting tomorrow. I agree that it is not a reason for blocking publications, but the way it is for me looks like a bug, something convenient but that it was not well planned, and that it is not a transparent action for the users.

**Comment by AgustinVallejo** [comment]
@jessegreenberg and I added the missing a11y features for StopwatchNode.

We're also on the fence about adding groupHighlighting to the stopwatch and period timer, as it was discussed on a previous meeting. This is how it looks, what do you think @DianaTavares @arouinfar ?

![image](https://github.com/phetsims/keplers-laws/assets/37052186/6ea9b05f-6764-48dd-9638-b17d1df62707)

![image](https://github.com/phetsims/keplers-laws/assets/37052186/6f1fc010-00cb-4c3a-b60c-e6239471647d)

**Comment by arouinfar** [comment]
> We're also on the fence about adding groupHighlighting to the stopwatch and period timer

I'm fine with it either way, but curious to hear what @DianaTavares thinks.

**Comment by DianaTavares** [comment]
I think it is ok!!

**Comment by Nancy-Salpepi** [comment]
All looks good in rc.2
Closing!
