### ISSUE TITLE
Stopwatch timer is not scaled equal to the sim

### ISSUE THREAD

**Issue by AgustinVallejo** [phetsims/keplers-laws#175]
Noticed during https://github.com/phetsims/qa/issues/984, when switching between slow, normal, fast, the readout of the stopwatch is always the same.

**Comment by KatieWoe** [comment]
I noticed this as well. While the speed options seemed fixed on main, I did see that if the sim is paused and stepped forward, the stopwatch does not count up. Reopening since this seems like the same issue, but if you want a new one, let me know.

**Comment by AgustinVallejo** [comment]
Oh thanks! Didn't notice that. Seems fine on this issue.

**Comment by KatieWoe** [comment]
One more point about the stopwatch. If it is still going when you uncheck it's box, then bring it back it will still be at the reading it was before. Is this the desired behavior?

**Comment by AgustinVallejo** [comment]
I think it should be done now. Could you please review and close if done? Thanks!

**Comment by KatieWoe** [comment]
Looks good! Normally these are left open to verify in the next rc, and closed then. Which would you prefer?

**Comment by Nancy-Salpepi** [comment]
Looks good in rc.2!
