### ISSUE TITLE
Long warning strings

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/keplers-laws#177]
**Test device**
iPad
**Operating System**
iPadOS 17.0.1
**Browser**
Safari
**Problem description**
For https://github.com/phetsims/qa/issues/984
If strings are long (`?stringTest=double` or `?stringTest=long`) then the warning that an orbit is too small or large overlaps with the toolbox.

**Visuals**
![IMG_0009](https://github.com/phetsims/keplers-laws/assets/41024075/955c80d8-3130-44bf-b40a-c04678260642)
![IMG_0010](https://github.com/phetsims/keplers-laws/assets/41024075/de1db662-bec5-4693-beed-4ab9a0ecef8e)

**Comment by AgustinVallejo** [comment]
Changed the maxWidth. Please review and close

**Comment by KatieWoe** [comment]
Looks good on main. Should this be left open to verify in the next rc?

**Comment by KatieWoe** [comment]
I noticed that there's still some overlap on the left-hand side on other screens.
![IMG_0011](https://github.com/phetsims/keplers-laws/assets/41024075/b816f808-0db3-4c10-9cec-b7ee8da6a8f2)
![IMG_0012](https://github.com/phetsims/keplers-laws/assets/41024075/7fc99884-ffe7-4801-a3c2-11cf4c19e116)

**Comment by KatieWoe** [comment]
Looks good
