### ISSUE TITLE
Graph behavior inconsistent when moving Star Mass slider

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/keplers-laws#179]
**Test device**
MacBook Air M1 chip

**Operating System**
13.5.2

**Browser**
Safari 16.6

**Problem description**
For https://github.com/phetsims/qa/issues/984, on the Third Law Screen, if a white graph has already been drawn, moving the Star Mass slider, will alter the white line of the graph as the dot moves. If no graph has already been drawn, moving the Star Mass slider will move the dot in the graph, but won't create a line. 

**Steps to reproduce**
1. On the Third Law screen, move the body to create a line in the graph
2. Move the Star Mass slider --line and dot both move
3. Press either the Eraser button or the Reset All button
4. Move the Star Mass slider -- only the dot moves

**Visuals**

https://github.com/phetsims/keplers-laws/assets/87318828/e9f65a7d-e6fa-48d8-9292-7a9c7af07c80

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Kepler's Laws‬
URL: https://phet-dev.colorado.edu/html/keplers-laws/1.1.0-rc.1/phet/keplers-laws_all_phet.html
Version: 1.1.0-rc.1 2023-09-18 17:02:56 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36
Language: en-US
Window: 1345x718
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by AgustinVallejo** [comment]
This is now more consistent. Please review!

**Comment by Nancy-Salpepi** [comment]
Those behaviors are now more consistent. I'm still confused as to why moving the Star Mass Slider down to .5 gives only the arrow in the middle. The only time I see just the arrow in the middle is when I press the Eraser button. 

Steps:
1. Move the body to the right a little bit to create a graph
2. Move the Star Mass slider all the way to the left.

**Comment by AgustinVallejo** [comment]
Oh, this is a bit unfortunate but consistent. The arrow in the middle appears when the body is out of bounds but there's no drawn line to stick the arrow to. The white line goes from the minimum visited semi major axis and the maximum one. If either one of those is also beyond the scope of the graph, they won't get drawn.

When starting the screen and moving M=0.5, the initial semi-major axis will now have a period that's bigger than the maximum period shown in the graph. So no part of the line will be drawn and the out-of-bounds arrow goes to the middle.

**Comment by Nancy-Salpepi** [comment]
OK thank you. Then this is good. 
Keeping open for the next rc.

**Comment by Nancy-Salpepi** [comment]
This looks good in rc.2.
Closing.
