### ISSUE TITLE
Third law graph should be drawn by the position of the dot

### ISSUE THREAD

**Issue by AgustinVallejo** [phetsims/keplers-laws#18]

**Comment by samreid** [comment]
This is mostly working, but when dragging the slider quickly to the left, we see an unexpected trace. Maybe @jonathanolson could help us solve it?

**Comment by AgustinVallejo** [comment]
To document more on this error: We're telling ThirdLawGraph to listen for the changedEmitter in the orbit, adjust the min and max of the graph path, and draw. Also, we're telling it to reset min and max when Mass is updated, so the line is deleted. However, it's going along these lines: 
- Mass edited > line is deleted > Orbit is updated because mass changed (we also saw this step happens like 7 times) > Line is drawn again for the changes during this step.

**Comment by AgustinVallejo** [comment]
The phantom line bug is kind of gone, but not completely. Right now you can move the mass slider quickly and it shows, but disappears as soon as you let go of the slider. Should I try to fix that as well or is this acceptable behavior? @arouinfar @DianaTavares 
![image](https://user-images.githubusercontent.com/37052186/232899983-3af161a8-1f43-4197-9a0c-dc51b8919caa.png)

**Comment by AgustinVallejo** [comment]
Action items:

- [ ] Make title dynamic
- [ ] Change style of line
- [ ] Add out of bounds arrow https://github.com/phetsims/keplers-laws/issues/13
- [ ] Remove clip bounds on 0,0

The behavior of the graph when mass changes is still open for discussion.

**Comment by AgustinVallejo** [comment]
A question regarding this. In the last design meeting it was decided that mass slider changes should not draw on the graph. However, if somebody by dragging the body marks the line [10 - 50], then slides the mass so the body is now at 60 and drags the body around from 60 to 70, should we expect discontinuities in the line??
