### ISSUE TITLE
Graph arrow doesn't appear in screenshot 

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/keplers-laws#180]
**Test device**
MacBook Air M1 chip

**Operating System**
13.5.2

**Browser**
Safari/Chrome  (also Win10 + FF)

**Problem description**
For https://github.com/phetsims/qa/issues/984, on the Third Law Screen if I take a screenshot from the PhET Menu, the arrow in the graph doesn't appear. The pink dot does. 

**Steps to reproduce**
1. On the Third Law Screen, move the body until a line with an arrow appears in the graph
2. Take a screenshot from the PhET Menu

**Visuals**
In the sim:

<img width="341" alt="Screenshot 2023-09-26 at 2 32 32 PM" src="https://github.com/phetsims/keplers-laws/assets/87318828/623a8e7c-9b65-4333-b7a5-4aa4cd4e8821">

In the screenshot:
<img width="341" alt="Screenshot 2023-09-26 at 2 32 21 PM" src="https://github.com/phetsims/keplers-laws/assets/87318828/53974f26-eee0-420d-bd3d-c52f76c37e2a">

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Kepler's Laws‬
URL: https://phet-dev.colorado.edu/html/keplers-laws/1.1.0-rc.1/phet/keplers-laws_all_phet.html
Version: 1.1.0-rc.1 2023-09-18 17:02:56 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36
Language: en-US
Window: 1345x718
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by AgustinVallejo** [comment]
Got inspired by https://github.com/phetsims/my-solar-system/issues/52 to fix this. Please review!

**Comment by Nancy-Salpepi** [comment]
The arrow is now in the screenshot, but the entire panel moves now.

https://github.com/phetsims/keplers-laws/assets/87318828/b0164916-d6db-4d61-9fc5-2b489120339d

**Comment by AgustinVallejo** [comment]
Improved the padding for the contents of the graph. Please review @Nancy-Salpepi, and thanks!

**Comment by Nancy-Salpepi** [comment]
Looks good 🙂. Keeping open for the next rc.

**Comment by KatieWoe** [comment]
Looks good in rc.2
