### ISSUE TITLE
Metronome sound heard when pressing the Eraser button

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/keplers-laws#181]
**Test device**
MacBook Air M1 chip

**Operating System**
13.5.2

**Browser**
Chrome

**Problem description**
For https://github.com/phetsims/qa/issues/984, on the Second Law screen I hear the Metronome sound instead of the Eraser sound if I press the Eraser Button while the sim is playing. 

**Steps to reproduce**
1. Go to the Second Law screen and press play
2. Press the Eraser button multiple times while an area is being swept

**Visuals**

https://github.com/phetsims/keplers-laws/assets/87318828/ff40110a-9acc-4cae-a59b-b6bbb61ab1d5

<details>
**Test device**

**Operating System**

**Browser**

**Problem description**

**Steps to reproduce**

**Visuals**

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Kepler's Laws‬
URL: https://phet-dev.colorado.edu/html/keplers-laws/1.1.0-rc.1/phet/keplers-laws_all_phet.html
Version: 1.1.0-rc.1 2023-09-18 17:02:56 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36
Language: en-US
Window: 1345x718
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by AgustinVallejo** [comment]
Ready to review!

**Comment by Nancy-Salpepi** [comment]
This looks good too! 
Keeping open for the next rc.

**Comment by KatieWoe** [comment]
Looks good in rc.2
