### ISSUE TITLE
Audio distortion for Firefox only

### ISSUE THREAD

**Issue by JaronDroder** [phetsims/keplers-laws#182]
Test device
 Alienware m15 R7 

Operating System

Window 11 22H2

Browser

Firefox , 117.0.1

Problem description

On Firefox and for all screens of the sim, I've found the audio with moving the planet as well as other options like moving the star mass slider, the audio made by the sim is distorted and crackling.  For chrome, I found the audio did not have this same distortion. 

Steps to recreate

Move the planet on any window, or on the third law and all laws screen, move the star mass slider to either end. 
Visuals

https://github.com/phetsims/keplers-laws/assets/115029534/4b68bd83-288b-46b8-9a30-05bc0f079a33

**Comment by Nancy-Salpepi** [comment]
I also hear this on my Dell with FF.

**Comment by AgustinVallejo** [comment]
Also paging @jbphet

**Comment by AgustinVallejo** [comment]
Worked with @jbphet in a possible solution. Can you check if this is fixed @JaronDroder? Thanks!

**Comment by JaronDroder** [comment]
@AgustinVallejo I am still getting the noise distortion on firefox

**Comment by KatieWoe** [comment]
Linking to https://github.com/phetsims/qa/issues/984

**Comment by JaronDroder** [comment]
@AgustinVallejo The issue seems to have been resolved.

**Comment by Nancy-Salpepi** [comment]
For rc.2 the continuous static is gone. I hear a crackle every once in a while, but overall this is much improved. 
Closing!
