### ISSUE TITLE
Info button very close to text

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/keplers-laws#183]
**Test device**
MacBook Air M1 chip

**Operating System**
13.5.2

**Browser**
Safari/Chrome

**Problem description**
For https://github.com/phetsims/qa/issues/984, on the First Law screen when the Eccentricity panel isn't visible the info button is very close to the values for "a" and "b". Do you think it would be better to have a little space here?

Similarly, the info button is very close to the value for "|r|" without the Eccentricity panel. 

**Visuals**
<img width="191" alt="Screenshot 2023-09-27 at 8 10 24 AM" src="https://github.com/phetsims/keplers-laws/assets/87318828/eddccc27-e091-4eac-b270-641e154bd8b3">

<img width="211" alt="Screenshot 2023-09-27 at 8 17 54 AM" src="https://github.com/phetsims/keplers-laws/assets/87318828/6c62b03b-3120-4be7-a271-9899769982d0">

**Comment by AgustinVallejo** [comment]
Added spacing. Please review.

**Comment by KatieWoe** [comment]
Looks ok to me in rc.2
