### ISSUE TITLE
Some variables are hard to read in projector mode

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/keplers-laws#184]
**Test device**
MacBook Air M1 chip/Dell

**Operating System**
13.5.2/Win10

**Browser**
Safari/Chrome

**Problem description**
For https://github.com/phetsims/qa/issues/984, the fluorescent green color in the More Orbital Data panel is hard to decipher when in projector mode. I'm not sure if students in the back of a classroom would be able to read it. Is there another option?

**Visuals**
<img width="264" alt="Screenshot 2023-09-27 at 8 36 01 AM" src="https://github.com/phetsims/keplers-laws/assets/87318828/87597cdc-240c-4bbc-8d88-044e06f085c1">

**Comment by AgustinVallejo** [comment]
I took the liberty of using a darker shade of green. Let me know if you think it's fine or would you prefer another tone @DianaTavares 

![image](https://github.com/phetsims/keplers-laws/assets/37052186/c22cd4bc-601d-4e9c-aacf-900c96e5dd4e)

**Comment by KatieWoe** [comment]
In my opinion the tan is still a bit hard to see. In addition, I notice that the lime green of the velocity vector may be a good thing to change in projector mode too.

**Comment by Nancy-Salpepi** [comment]
Looks good to me in rc.3.
