### ISSUE TITLE
Adding More Data panel to Second Law but not in All Laws mode

### ISSUE THREAD

**Issue by AgustinVallejo** [phetsims/keplers-laws#185]

**Comment by KatieWoe** [comment]
This is done in rc.2, but the text in the preferences menu does not show it. Should the text be changed?
![shouldchange](https://github.com/phetsims/keplers-laws/assets/41024075/1d9315a0-7edb-48f2-9c14-f2b38c66dd4a)

**Comment by AgustinVallejo** [comment]
It should! I'll update soon

**Comment by Nancy-Salpepi** [comment]
This looks good to me in rc.3.
Closing.
