### ISSUE TITLE
Period Timer value doesn't reset with Reset All

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/keplers-laws#186]
**Test device**
MacBook Air M1 chip

**Operating System**
14.0

**Browser**
Safari 17

**Problem description**
For https://github.com/phetsims/qa/issues/990, if the period timer is done timing, pressing Reset All will not reset the time back to 0.

**Steps to reproduce**
1. On the Third Law screen, check Period checkbox
2. Press Play on the Period Timer
3. Press Play button for the sim
4. Once the period timer is done, press Reset All
5. Check the Period checkbox

**Visuals**

https://github.com/phetsims/keplers-laws/assets/87318828/d802e015-4d7c-4825-9ef6-7f7750ba2321

**Comment by KatieWoe** [comment]
This seems fixed in rc.4
