### ISSUE TITLE
Keyboard help is missing for combo box.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/keplers-laws#188]
Sorry to report this for RC spot-check https://github.com/phetsims/qa/issues/990 ...

Similar to https://github.com/phetsims/my-solar-system/issues/200 ...

All of the screens in this sim appear to be using the same keyboard help: `KeplersLawsKeyboardHelpContent`.  But 3 of the 4 screens have a 'Target Orbit' combo box:

<img width="256" alt="screenshot_2810" src="https://github.com/phetsims/keplers-laws/assets/3046552/3f8476cf-94f3-4bf3-b2cf-f943f9b09c49">

... and help for that combo box (`ComboBoxKeyboardHelpSection`) is missing for those screens.

**Comment by pixelzoom** [comment]
Below is an example of how `ComboBoxKeyboardHelpSection` is used, from Geometric Optics.  

<img width="928" alt="screenshot_2806" src="https://github.com/phetsims/keplers-laws/assets/3046552/d4e87a5e-299e-4ef0-9abe-8786eca1e28c">

The langugage can be customized to the type of item being selected.  You'll probably want to substitute "Target Orbit" for "Object", like this:

```ts
      // Choose a Target Orbit
      new ComboBoxKeyboardHelpSection( {
        headingString: KeplersLawsStrings.keyboardHelpDialog.chooseATargetObjectStringProperty,
        thingAsLowerCaseSingular: GeometricOpticsStrings.targerObjectStringProperty,
        thingAsLowerCasePlural: GeometricOpticsStrings.keyboardHelpDialog.targetObjectsStringProperty
      } )
```

Note that you'll need 2 new strings: 

```
  "keyboardHelpDialog.chooseATargetObject": {
    "value": "Choose a Target Object"
  },
  "keyboardHelpDialog.targetObjects": {
    "value": "Target Objects"
  },
```

**Comment by pixelzoom** [comment]
The end result should look like this:

<img width="421" alt="screenshot_2808" src="https://github.com/phetsims/keplers-laws/assets/3046552/908235ae-9f17-4573-a0fa-97d0ee5b7723">

**Comment by AgustinVallejo** [comment]
Although with the current amount of Keyboard contents, this seems a bit crowded... Don't know if there's a better possible layout for these cases, or if not including the combo box help is even an option.

![image](https://github.com/phetsims/keplers-laws/assets/37052186/20bf0299-9f2f-46c7-9dc2-fd1cb1ff08fb)

@arouinfar @DianaTavares

**Comment by arouinfar** [comment]
> this seems a bit crowded.

I agree, but it's acceptable.

> Don't know if there's a better possible layout for these cases, 

I would have moved the "Move Draggable Items" to the top of the right column to even things out. However, I didn't see this issue until the sim was in spot-check. Next time please assign me when you want feedback, @AgustinVallejo.

> or if not including the combo box help is even an option.

We should definitely include ComboBox instructions for relevant sims. I'd forgotten that there was a KeyboardHelpSection for this, thanks @pixelzoom.

**Comment by KatieWoe** [comment]
The instructions show up, but they show up on all screens, even though the Second Law screen does not have a combo box

**Comment by pixelzoom** [comment]
It looks like there's still a single `KeplersLawsKeyboardHelpContent` being used for both screens.  Since the keyboard help needs are different for each screen, they need to have their own keyboard help classes -- `IntroKeyboardHelpContent` and `LabKeyboardHelpContent` for the Intro and Lab screens respectively.

**Comment by pixelzoom** [comment]
It looks like there's still a single `KeplersLawsKeyboardHelpContent` being used for both screens.  Since the keyboard help needs are different for each screen, each screen should have its own keyboard help content class. Or you could add a `hasComboBoxHelp: boolean` option to `KeplersLawsKeyboardHelpContent`, and set it to `true` only for the screens that have a combo box.

**Comment by AgustinVallejo** [comment]
Didn't know it was different for each screen. Changing.

**Comment by pixelzoom** [comment]
@AgustinVallejo and I did a bit of work on this, and the ComboBoxKeyboardHelpSection is now created conditionally.

We also decided that the ComboBoxKeyboardHelpSection is best in the lower-left of the dialog, because it's not present for all screens. Putting it elsewhere results in a lopsided dialog for screens that do not have a combo box.

**Comment by KatieWoe** [comment]
This looks fixed in rc.5
