### ISSUE TITLE
Third law graph panel should also be an accordion box

### ISSUE THREAD

**Issue by AgustinVallejo** [phetsims/keplers-laws#19]

**Comment by samreid** [comment]
I wrote an initial draft, but there is asymmetry in how the panels in different screens are treated, see this code:

```ts
          new FirstLawPanels( model ),
          new SecondLawPanels( model ),
          new ThirdLawAccordionBox( model )
```

And the SecondLawPanel just contains an accordion box.  This should be simplified and clarified.

**Comment by samreid** [comment]
I think the solution is to move in this direction:

<details>

```diff

Subject: [PATCH] Show the third law graph and panel in an accordion box, see https://github.com/phetsims/keplers-laws/issues/19
---
Index: js/keplers-laws/view/KeplersLawsScreenView.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/keplers-laws/view/KeplersLawsScreenView.ts b/js/keplers-laws/view/KeplersLawsScreenView.ts
--- a/js/keplers-laws/view/KeplersLawsScreenView.ts	(revision 1f9bfa17444c3b2c0d36f9ce8fb7f46696e031e4)
+++ b/js/keplers-laws/view/KeplersLawsScreenView.ts	(date 1681760598523)
@@ -9,7 +9,6 @@
 import { AlignBox, HBox, VBox } from '../../../../scenery/js/imports.js';
 import KeplersLawsModel from '../model/KeplersLawsModel.js';
 import KeplersLawsControls from './KeplersLawsControls.js';
-import SecondLawPanels from './SecondLawPanels.js';
 import BodyNode from '../../../../solar-system-common/js/view/BodyNode.js';
 import EllipticalOrbitNode from './EllipticalOrbitNode.js';
 import ThirdLawAccordionBox from './ThirdLawAccordionBox.js';
@@ -26,6 +25,7 @@
 import DistancesDisplayNode from './DistancesDisplayNode.js';
 import keplersLaws from '../../keplersLaws.js';
 import NumberProperty from '../../../../axon/js/NumberProperty.js';
+import SweptAreaAccordionBox from './SweptAreaAccordionBox.js';
 
 // constants
 const MARGIN = 10;
@@ -120,7 +120,7 @@
     const lawsAndZoomBoxes = new AlignBox( new HBox( {
         children: [
           new FirstLawPanels( model ),
-          new SecondLawPanels( model ),
+          new SweptAreaAccordionBox( model ),
           new ThirdLawAccordionBox( model )
           // NOTE: CODE TEMPORARILY COMMENTED OUT, AWAITING DESIGN DECISION
           // new MagnifyingGlassZoomButtonGroup(

```

</details>

But I wasn't sure about comments like `This class is mostly empty and only has SweptAreaAccordionBox as a child to keep code consistency across the three laws.` So I'll leave it up to @AgustinVallejo to decide on this part.  Note that ThirdLawPanels is the nested content in its accordion box, so if we bring back SecondLawPanels in that array, we will need a new placeholder object (not sure if that is the right way).

**Comment by AgustinVallejo** [comment]
Hi, made it simetric in KeplersLawsScreenView by using ThirdLawsPanels (Includes ThirdLawAccordionBox and ThirdLawSliderPanel, only the first one should be accordion)... There's still work to do on:

- [ ] Fixing the behavior in ThirdLawPanels where if you close the accordeon, the second Panel should probably move up and fill the gap?
- [ ] Deciding if we want the panels across the three screens to be consistent in width.
- [ ] Will all this work with dynamicStrings?
