### ISSUE TITLE
KeplersLawsModel overwrites `defaultBodyState` in superclass

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/keplers-laws#192]
Discovered while adding missing `readonly` keywords in https://github.com/phetsims/my-solar-system/issues/214 ...

In SolarSystemCommonModel, `defaultBodyState` should be readonly, and it's assigned once in the constructor:

```ts
  protected defaultBodyState: BodyInfo[];
...
    this.defaultBodyState = this.availableBodies.map( body => body.info );
```

class KeplersLawsModel extends SolarSystemCommonModel, and overwrites `defaultBodyState`:

```ts
    this.defaultBodyState = [
      { active: true, mass: 200, position: new Vector2( 0, 0 ), velocity: new Vector2( 0, 0 ) },
      { active: true, mass: 50, position: new Vector2( 200, 0 ), velocity: new Vector2( 0, 81.6 ) }
    ];
```

`defaultBodyState` should be added as an option to SolarSystemCommonModelOptions.

**Comment by AgustinVallejo** [comment]
Made the above changes to correct this, let me know if they seem like the right approach.

**Comment by pixelzoom** [comment]
Looks good, and `defaultBodyState` is now `readonly`. Closing.
