### ISSUE TITLE
Kepler's Laws postmortem

### ISSUE THREAD

**Issue by AgustinVallejo** [phetsims/keplers-laws#194]
# Kepler's Laws postmortem

- [x]  **1. Schedule the meeting**
- Invite the entire sim team to participate, and optionally anyone else who had a significant involvement. Have the
  meeting as soon as possible after the sim is released, so that experiences are still fresh in everyone's mind. Allow
  sufficient time for the meeting, 1.5-2 hours.

- [x]  **2. Enlist a meeting moderator:** @marlitas 
- The moderator's job is to make sure the meeting runs efficiently, stays on point, and focuses on constructive (but not
  overly negative) criticism. The moderator can be someone not on the sim team, or in many cases the Development
  Coordinator. The moderator also documents the important points of the meeting.

- [x]  **3. Create github postmortem issue and postmortem google doc**
- Create a GitHub issue in the repository of the sim for which the postmortem is occurring. This checklist will should
  be copied into the issue.
- [Postmortem Google Doc](https://docs.google.com/document/d/1bRMglwqW79IpTrH2huRsvAkCUAXSaUUkZ6p4hVTusAQ/edit?usp=sharing)

- [x]  **4. Two successes and two improvements**
- Participants will bring a list of no more than 2 items that were done well during the project and no more than 2
  items that could be improved upon. Limiting to 2 requires people to think critically about their experience.

- [x]  **5. Identifying the top five**
- At the meeting, start by having each person present their items (successes, then improvements). Make a list of these
  items, and note duplicates. Based on popularity, identify the top 5 success items and the top 5 items that need
  improvement.

* Discuss the 5 success items first. Identify specific things that can be applied to future sims. Celebrate, pat each
  other on the back. Then move on to the harder part.
* Discuss the 5 improvement items. Try to avoid getting personal. Discuss what was learned, and identify specific things
  that can be done to prevent these problems in the future. If anything needs more investigation, assign to specific
  individuals.

- [ ]  **6. Modifications to Look & Feel**
- Identify modifications to the PhET Look-&-Feel Guidelines. If applicable, based on what we learned during development
  of this sim, suggest revisions to the guidelines.

* [HTML5 Look and Feel](https://docs.google.com/document/d/1Fg4E6VNMsnId7CjsyqHKnZeIoQ4N-5ezM9PTkj7N3PM/edit)
* [HTML5 Visual Sim Design Elements
  ](https://docs.google.com/document/d/1rpp0vT7-bGUs_5tZP_77-HM8PnaGbIDQ5DGNygX5CBo/edit)

- [ ]  **7. Sim checklist**
- Review the [Sim Checklist](https://github.com/phetsims/phet-info/blob/main/checklists/sim-checklist.md)

- [ ]  **8. Action items**
- Note important items in the postmortem GitHub issue, and create issues for any tasks the require action (such as
  updating documents, leftover TODOs, etc.
- Action Item Questions:
  - Modifications to look and feel?
  - Modifications to sim design process?
  - Modifications to project process?
  - Messages to share at status?

- [ ]  **9. Take home messages**
- From the top 5 successes/improvements, decide what are the "take home" messages that would be useful to note in the
  future, and add these to the [HTML5 Postmortem Take Home Messages](https://docs.google.com/document/d/1hayLX0FbhYqGao-5xizAFU9kVBzqrW_RVX88Wk_C_Lc/edit#heading=h.krbf2d24bpav) Google doc
- Report out at status meeting

**Comment by pixelzoom** [comment]
The post mortem is scheduled for 11/7 @ 11:00AM MT.  I've assigned this issue to everyone who is invited to the meeting, so that they are aware of what needs to be done prior to the meeting.  Specifically see item 4 above.

**Comment by marlitas** [comment]
@AgustinVallejo, I believe a person from outside of the sim team needs to be the moderator. I will be the moderator for this particular post-mortem. I'll update the comment above.

**Comment by marlitas** [comment]
### Action Items

- Modifications to look and feel?
  - AV: There is confusion around the cueing-arrow node.
    - CM: This has come up repeatedly for a very long time and has never been resolved.
    - AV: This is still in the document for “look and feel”. Perhaps this should be updated or revised?
    - AR: The look and feel doc is very antiquated and not maintained. 
    - CM: Preferences needs “look and feel” work as well and it hasn’t happened. The longer we wait the harder it is to update all of them, and students start to get confused when it’s no longer standard.
  - No action item, but we all know work needs to be done…
- Modifications to sim design process?
  - More interviews earlier on in the process with teachers (in the wireframe stage).
    - DL: We can also use our fellows. This is a close community of teachers that we can communicate the design process a bit more. 
  - UI design: Start with low-fidelity wireframes or sketches before progressing to hi-fidelity mockups
    - CM: Some pushback is that people feel that hi-fi is necessary to sell the sim. This just requires more imagination and practice. We should be able to iterate on lo-fi visuals to spend less resources on polishing the visual and more time on the discussion.
    - AR: The more complex bits may be harder to communicate via lo-fi visuals, but in general this shift would be a large efficiency improvement. When visuals are polished people talk about the UI instead of the UX, and the UX is the important part at this stage.
    - AR: Perhaps we have a designer debrief after the CAV post-mortem
    - AV: Perhaps a PhET-wide designers meeting would help with the institutional knowledge that gets passed on. 
    - AR: Maybe a monthly meeting/forum to discuss and connect? It could cover general design questions/user flow. 
    - AR/DL: the slack channel doesn’t feel useful for this all the time.
  - Schedule a monthly (or quarterly) designers meeting for designers to gather and talk through general questions. 
- Modifications to project process?
  - Consider PhET-iO in every project. Even if it might not be supported in this publication, it needs to be part of the design/dev process. We have committed to PhET-iO and having to come back later and do a retro-fit is undesirable and costly.
    - AR: It’s harder in general for a phet-io retro-fit. Revisiting after a long time away makes it harder to address. Even if the sim is in good shape.
    - CM: It has to be considered during implementation even if the upcoming publication is not supporting it. We need to minimize retro-fit cost.
- Messages to share at status?
  - We would like to try doing more interviews with teachers in the wireframe stage.
  - All new projects should either support PhET-iO or have a plan for how the sim will support PhET-iO in the future.
  - The possibility of creating a “Designer” meeting.
- Modifications to post-mortem checklist?
  - MS will check on links, and update it.

### Take Home Messages

- Post-mortems need to be scheduled for more than an hour. (MS will check in with website team for CAV post-mortem)

**Comment by arouinfar** [comment]
Post-mortem take-home messages were shared at the 11/30/2023 status meeting. I don't think there's anything else to do for this issue, closing.

> We would like to try doing more interviews with teachers in the wireframe stage.

We are currently trying this out in Buoyancy.

> The possibility of creating a “Designer” meeting.

We created a Designers meeting that currently meets once per iteration.
