### ISSUE TITLE
Distance from planet to sun assumes that sun is at (0,0)

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/keplers-laws#196]
In MoreOrbitalDataPanel, here's the code that computes the distance from the planet to the sun:

```ts
    const positionMagnitudeStringProperty = new PatternStringProperty( KeplersLawsStrings.pattern.valueUnitsStringProperty, {
      units: KeplersLawsStrings.units.AUStringProperty,
      value: new DerivedProperty( [ model.planet.positionProperty ], position => {
        return Utils.toFixed( position.magnitude, 2 );
      } )
    } );
```

This assumes that the sun is a (0,0).  I'd say that a dangerous assumption, and not a reasonable way to compute distance.  Especially when `sun.positionProperty` is currently mutable via PhET-iO.

**Comment by pixelzoom** [comment]
I suspect that there is more code in MoreOrbitalDataPanel that is assuming that the sun is at (0,0).  Anytime that has a dependency on `planet.positionProperty` is suspect, and that includes `distanceAngleStringProperty` and `rvAngleStringProperty`.   So I'm going to assign this to @AgustinVallejo and let him take it from here.

**Comment by pixelzoom** [comment]
This also looks suspect in EllipticalOrbitEngine:

```ts
    Multilink.multilink(
      [ this.planet.positionProperty, this.planet.velocityProperty, this.sun.massProperty ],
      ( position, velocity, mass ) => {
        const rMagnitude = position.magnitude;
```

If you don't want to fix these assumption, then it would be worth adding an assertion like:

```ts
assert && assert( sun.positionProperty.equals( Vector2.ZERO ) );

**Comment by AgustinVallejo** [comment]
We can discuss this tomorrow. It's not only that we assume that position, but all the orbital equations are made with that coordinate frame in mind. I think the best solution is either the assertion or to link the entire orbit and its calculations to the position of the sun body, because otherwise it wont make any sense.

**Comment by pixelzoom** [comment]
Adding the assertion that the sun is at (0,0) would be fine.  And document that "the orbital equations are made with that coordinate frame in mind".   That's will not be obvious to some maintaining or reusing the code.

**Comment by pixelzoom** [comment]
@AgustinVallejo added a listener in the above commit that addresses this:

```ts
  this.sun.positionProperty.link( position => {
      assert && assert( position.equals( Vector2.ZERO ), 'This sim requires the sun to be at the origin always!' );
    } );
```

We'll need to make sure that sun.positionProperty can't be changed, but that can be deferred for future work on a PhET-iO version of this sim.

Closing.
