### ISSUE TITLE
Bodies are moving faster than they were previously

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/keplers-laws#200]
In https://github.com/phetsims/qa/issues/998#issuecomment-1781576827, @KatieWoe noted:

> I noticed that the speed of a planet in dev 2 is faster than in dev 1. Not by the stop watch, but in real time. Is this intended, or a bug?

This is undoubtedly caused by https://github.com/phetsims/my-solar-system/issues/252.  Maybe it's OK, maybe not -- I'm not sure.

This may also be related to https://github.com/phetsims/my-solar-system/issues/257.  Bodies moving faster would result in longer line segments used to draw the path, which could make it appear less smooth.

**Comment by pixelzoom** [comment]
@Nancy-Salpepi can you report on whether you also see this problem in My Solar System for https://github.com/phetsims/qa/issues/997. I'll be surprised if this is not a problem there too.  If that's the case, then we should transfer this issue to my-solar-system repo.

**Comment by AgustinVallejo** [comment]
After close inspection, the above commit makes the time scale the same as it was for the baseline in Kepler. 
The difference in My Solar System is of 1s, I'll investigate if it is causing the path anomalies, but I think this particular issue can be closed.
