### ISSUE TITLE
Velocity adjusts very slowly with alt input

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/keplers-laws#202]
**Test device**
MacBook Air M1 chip

**Operating System**
14.0

**Browser**
Safari 17

**Problem description**
For https://github.com/phetsims/qa/issues/998, moving the velocity vector with alt input happens a lot slower in 1.2.0-dev.3 than in 1.2.0-dev.1.

**Steps to reproduce**
1. On any screen, tab to the Velocity Vector and use arrow keys to move it
2. Compare with dev.1

**Visuals**
Video starts in dev.3 and then switches to dev.1:

https://github.com/phetsims/keplers-laws/assets/87318828/7401a92d-db07-4340-94bb-7356f58bb0e7

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Kepler's Laws‬
URL: https://phet-dev.colorado.edu/html/keplers-laws/1.2.0-dev.3/phet/keplers-laws_all_phet.html
Version: 1.2.0-dev.3 2023-10-26 19:57:12 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Safari/605.1.15
Language: en-US
Window: 1410x711
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by pixelzoom** [comment]
@AgustinVallejo do the `dragVelocity` and `shiftDragVelocity` values to DraggableVelocityVectorNode need to be adjusted? They are `450` and `100` respectively in solar-system-common (and my-solar-system by default), but `150` and `50` in keplers-laws.

**Comment by AgustinVallejo** [comment]
Will look into it

**Comment by pixelzoom** [comment]
We should check if this difference also exists for dragging bodies.

**Comment by pixelzoom** [comment]
It is not a problem for BodyNode in either sim.

It is a problem for DraggableVelocityVectorNode is both sims.

**Comment by AgustinVallejo** [comment]
In the above commit I changed both the default and Kepler's. I think since the units change I hadn't updated the dragVelocity

**Comment by pixelzoom** [comment]
Since the model coordinate system and the model-view transform have changed, it's difficult to get the keyboard drag behavior to be identical to the baseline dev versions.  The values for `dragVelocity` and `shiftDragVelocity` are somewhat arbitray anyway.  So we played around with their values until the behavior felt good -- not identical to what it was, but usable.

@Nancy-Salpepi could you please have another look at both sims? Close if the behavior seems reasonable now.

**Comment by Nancy-Salpepi** [comment]
Behavior is much better in both sims. Closing.
