### ISSUE TITLE
Base level PhET-iO instrumentation

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/keplers-laws#206]
Much of the instrumentation has been done as the result of instrumenting My Solar System in https://github.com/phetsims/my-solar-system/issues/237.  

@AgustinVallejo and I discussed what remains for this sim, and the biggest tasks are:

* Use `Tandem.OPT_OUT` where needed to uninstrument things that are not relevant, based on reviewing the Studio tree. For example, `firstLawScreen.view.panels.secondLawPanels` is not relevant for the "First Law" screen.  This will probably involved changing KeplersLawsModelOptions `isAllLaws?: boolean` to something like that indicates which screen.

* Use `phetioReadOnly: true` for things that were editable in MSS but should not be in KL.  For example, should `sun.massProperty be editable`? This will require reviewing the Studio tree, and discussing with Amy.

* Identify any remaining elements that need to be stateful - for example see https://github.com/phetsims/keplers-laws/issues/201

**Comment by pixelzoom** [comment]
Also note that changes to `solar-system-common` should be made with the utmost caution. We do not want to change MSS. But we have not yet generated its API file, so githooks will not prevent you from changing the MSS API.

**Comment by pixelzoom** [comment]
I generated the API file for MSS, and turned on checking by CT and git-hooks.  So we are now protected from unintentional changes to the MSS API.

**Comment by pixelzoom** [comment]
@AgustinVallejo another significant task will be to identify any remaining elements that need to be stateful - for example https://github.com/phetsims/keplers-laws/issues/201.

**Comment by AgustinVallejo** [comment]
Published baseline versions for Kepler's Laws:
- https://phet-dev.colorado.edu/html/keplers-laws/1.2.0-dev.5/phet/keplers-laws_all_phet.html
- https://phet-dev.colorado.edu/html/keplers-laws/1.2.0-dev.5/phet-io/

**Comment by AgustinVallejo** [comment]
In this comment I'll be adding what should be taken out of Keplers that's currently instrumented in solar-system-common:
- [ ] `model.numberOfActiveBodies`: This is redundant, and unnecessary in Kepler's, as there'll always be two bodies.

**Comment by pixelzoom** [comment]
In the above commits, @AgustinVallejo and I paired on addressing the checklist items in https://github.com/phetsims/keplers-laws/issues/206#issuecomment-1813004936.

**Comment by pixelzoom** [comment]
Since the tree has been reviewed, this can be closed.
