### ISSUE TITLE
Identify fields that may need to be stateful

### ISSUE THREAD

**Issue by AgustinVallejo** [phetsims/keplers-laws#209]
Related to https://github.com/phetsims/keplers-laws/issues/206 I'll be editing this comment with new features to instrument.

- [x] Stopwatch reset button (11/16: We don't need to include this)
- [x] selectedLawProperty
- [x] (D) Zoom level kinda starts in the middle of the animation when testing standard wrapper 
- [x] All the physical properties included in the engine should be instumented and grouped together.
- [x] (D) Everything in MoreOrbitalData
- [x] (D) The result of T/a
- [x] hasUserInteractedProperty
- [x] #214
- [x] Drawn line in third law

I'm noting with (D) the ones which are derived properties.

**Comment by AgustinVallejo** [comment]
Although looking at `MoreOrbitalDataPanel.ts` it seems everything showed in there is derived from the planet's position and velocity properties. Should we still include those? @arouinfar

**Comment by AgustinVallejo** [comment]
As for the zoom issue, we're going to use `isSettingPhetioStateProperty` in the `zoomLevelProperty.link` to avoid doing the animation

**Comment by AgustinVallejo** [comment]
The initial list of things that needed instrumentation has been covered. Marking the issue ready for review, and please add anything missing instrumentation.

**Comment by pixelzoom** [comment]
@AgustinVallejo This is not typically something that the designer can review, because they don't see the internals of the code.  If there's something that's not stateful that should be (or something that should not be executed when state is being restore), then the State Wrapper will fail or behave incorrectly.  And that seems to be happening in #215.  So I suspect that this issue is not yet complete.

**Comment by pixelzoom** [comment]
Assigning myself, because this is something that another developer (me :) can review.

**Comment by pixelzoom** [comment]
From duplicate https://github.com/phetsims/keplers-laws/issues/201, here are a few more fields that might need to be stateful:

```ts
// KeplersModel
  public resetting = false;


// PeriodTracker
  public beganPeriodTimerAt = 0;
  public trackingState: TrackingState;
  public afterPeriodThreshold = false; // Whether the body has passed some percentage of the period


// PeriodTrackerNode
  public orbitScale = 1;
  public orbitCenter = Vector2.ZERO;
  public radiusX = 1;
  public radiusY = 1;
```

**Comment by pixelzoom** [comment]
PeriodTracker and PeriodTrackerNode were addreessed in #222.

@AgustinVallejo and I inspected KeplersModel `resetting` and didn't see any need for it to be stateful, or any related problems.

So closing this issue.
