### ISSUE TITLE
Instrumentation of Swept Areas

### ISSUE THREAD

**Issue by AgustinVallejo** [phetsims/keplers-laws#214]
For the swept areas logic to properly work, there's a bunch of internal number and boolean properties that keep track of their state. For PhET-iO they all had to be instrumented, with other on their way to be instrumented as well. Currently the three looks like this:

![image](https://github.com/phetsims/keplers-laws/assets/37052186/512530e7-3f15-4e0a-bdda-31b956b0cc31)

@arouinfar Do you think we should "un-feature" these properties? Or do you see any value in keeping them?

I'll also instrument in a moment the position and angle of the dots. In case any of those values is of any use.

**Comment by arouinfar** [comment]
@AgustinVallejo I reviewed the current structure on main. The organization in the tree looks good to me. Most of the properties look like internal plumbing that would be irrelevant to the clients, but it sounds like they are necessary to instrument for state. I think the best approach would be to add `phetioDocumentation` to indicate that they are for internal use and make sure that they are `phetioFeatured: false`.

The data relevant to clients is the `sweptAreaProperty` and potentially the `activeProperty` (but they could instead refer to`periodDivisionsProperty`). 

Unfortunately, `sweptAreaProperty` appears to be zero on startup, even though we see all areas fully filled, both in the play area and in the graph.
![image](https://github.com/phetsims/keplers-laws/assets/8419308/aa4f9e1a-9cf7-40ff-aa70-92f782b55b01)

The area value is corrected after the first time an area is swept, but the user would need to play the animation fully before the data in `sweptAreaProperty` is useful. Changing the number of period divisions also resets the values to zero.

Additionally, I think we should use 1-based indexing to align the orbital areas with their corresponding bar on the Swept Area graph.

> I'll also instrument in a moment the position and angle of the dots. In case any of those values is of any use.

I don't see any use for data about the dots @AgustinVallejo. I would skip this if it's not necessary for state.

**Comment by AgustinVallejo** [comment]
Did some improvements here. There's still a problem with the indexing, which doesn't correspond to the graph area. Will work on that later.

**Comment by AgustinVallejo** [comment]
> the only thing missing are the units
Units have been added. Feel free to close if ready @arouinfar

**Comment by arouinfar** [comment]
Thanks @AgustinVallejo, closing.

**Comment by AgustinVallejo** [comment]
Something to note about the area indexing: Before, they were ordered so the graph was always ascending. However, since each area is an PhET-iO object, we didn't want to change the indexes for consistency. So currently, the areas on the default orbit grow descendingly (2, 1, 3, 4) because it's counter clockwise. Other clockwise orbits do it correctly.
