### ISSUE TITLE
Planet sometimes jerks backwards when orbiting

### ISSUE THREAD

**Issue by AgustinVallejo** [phetsims/keplers-laws#219]
Specially in highly elliptical orbits such as the one attached, the planets orbits and every 2s it jerks backwards for a moment.

![image](https://github.com/phetsims/keplers-laws/assets/37052186/4390ea3d-44a1-420d-9346-87bae4572cfc)

**Comment by AgustinVallejo** [comment]
This is also happening in the baseline!

**Comment by AgustinVallejo** [comment]
It's also happening in the published version.

**Comment by AgustinVallejo** [comment]
Tried increasing the accuracy of a function in the engine. Could you briefly compare performance between main and the current rc version? To make sure lower end devices won't suffer from this change. @KatieWoe @Nancy-Salpepi

**Comment by KatieWoe** [comment]
This is what I see in the current RC 

https://github.com/phetsims/keplers-laws/assets/41024075/07c5b7f4-ea6e-4721-ac9e-81d2736ce3ef

**Comment by KatieWoe** [comment]
I did a quick on main on a chromebook. Things looked ok and any lag was minimal.

**Comment by Nancy-Salpepi** [comment]
I didn't observe any noticeable differences between rc.1 and main with Chromebook. There is a bit of jerkiness from time to time in both, but it is MUCH better than the current published version, which is pretty horrible with my Chromebook.

**Comment by Nancy-Salpepi** [comment]
Looks good on mac and iPad in rc.2
Will keep open for @KatieWoe to check on her devices.

**Comment by KatieWoe** [comment]
This looks ok to me
