### ISSUE TITLE
State is not restored for Period Tracker.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/keplers-laws#222]
PeriodTracker and PeriodTrackerNode are not properly restored in the Standard wrapper.  See screenshots below of Studio, and the corresponding Standard wrapper.  The blue line on the orbit is missing in the Standard wrapper.

Over in https://github.com/phetsims/keplers-laws/issues/209#issuecomment-1852722602, I identified these fields that may need to be stateful:

```ts
// PeriodTracker
  public beganPeriodTimerAt = 0;
  public trackingState: TrackingState;
  public afterPeriodThreshold = false; // Whether the body has passed some percentage of the period


// PeriodTrackerNode
  public orbitScale = 1;
  public orbitCenter = Vector2.ZERO;
  public radiusX = 1;
  public radiusY = 1;
```

<img width="1055" alt="screenshot_2930" src="https://github.com/phetsims/keplers-laws/assets/3046552/661ea7bd-aa94-4bd3-b31f-6ebe4754a15b">

<img width="1057" alt="screenshot_2931" src="https://github.com/phetsims/keplers-laws/assets/3046552/f7dae94e-2a3e-4e1e-9168-75657cecbd63">

**Comment by AgustinVallejo** [comment]
This is done. Assigning back for review, close if it looks okay. Naturally, this won't work if the sim is playing because of #215

**Comment by pixelzoom** [comment]
The documentation in EllipticalOrbitEngine indicates that these new Properties are only relevant for "Third Law":

```ts
  // These variables keep track of the period trace on Third Law (When the user measures period, a blue line will be traced)
  public readonly tracingPathProperty: BooleanProperty;
  public periodTraceStartProperty: NumberProperty;
  public periodTraceEndProperty: NumberProperty;
```

But these Properties now appear in the Studio tree for every screen.

**Comment by pixelzoom** [comment]
I'm also wondering why these Properties were added to EllipticalOrbitEngine instead of PeriodTracker.

**Comment by AgustinVallejo** [comment]
Good observation, I should probably move them and hide that tandem for other laws. Assigning myself.

**Comment by AgustinVallejo** [comment]
Did some work in here, but I'm not sure if I'm using the correct pattern. After moving the appropriate Properties into the PeriodTracker (PT), I got some circular dependencies (The engine now has to change values inside the PT, and the PT has to reference elements in the engine in the constructor). I ended up doing this in the engine:
```ts
public periodTracker: PeriodTracker | null;

// Originally set this to null. The model's Period Tracker will take its place after initialization.
this.periodTracker = null;
```
Then in `PeriodTracker.ts`
```ts
// Setting the engine's period tracker to this object here to avoid circular dependencies
this.model.engine.periodTracker = this;
```
Could you share your opinion on this @pixelzoom? If it's an unsafe pattern, let me know and we could pair on this tomorrow.

**Comment by pixelzoom** [comment]
Since EllipticalOrbitEngine and PeriodTracker both need to know about each other, I don't see any way around having to tell one of them about the other after instantiation.   But I think there's a cleaner way to do it, which I implemented https://github.com/phetsims/keplers-laws/commit/2271df3eccb99464658eb3cec801bc2d0b6edbd6.

To summarize the change... Rather than making PeriodTracker responsible for creating the connection between the 2 instances, KeplersLawsModels handles that.  And it does so by calling `engine.setPeriodTracker`, so that `this.periodTracker` can be private to EllipticalOrbitEngine.  So now we have this in KeplersLawsModel:

```ts
    this.engine = new EllipticalOrbitEngine( ... );
    this.engine.reset();

    this.periodTracker = new PeriodTracker( this.engine, ... );

    // EllipticalOrbitEngine and PeriodTracker need to know about each other, so we need to call this after they have
    // both been instantiated.
    this.engine.setPeriodTracker( this.periodTracker );
```
 
The other changes in the above commits involve cleaning up the constructor signatures for PeriodTracker and PeriodTrackerNode, so that it's obvious what they depend on.   Compare:

```ts
// KeplersLawsModel
- this.periodTracker = new PeriodTracker( this, ... );
+ this.periodTracker = new PeriodTracker( this.engine, this.timeProperty, ... );

// OrbitalEngineNode
- const periodTrackerNode = new PeriodTrackerNode( model, ... );
+ const periodTrackerNode = new PeriodTrackerNode( model.periodTracker, model.engine, ... );
```

I'm not a fan of using `Pick<...>` with parameters, especially when there are only a couple of parameters.  It feels lazy, and obfuscates dependencies. 

Back to @AgustinVallejo for review. Let me know if you have questions or would like to discuss.

**Comment by AgustinVallejo** [comment]
Thanks @pixelzoom, seems like a clean change. I was also thinking of creating a `setPeriodTracker`, but wasn't sure if it was okay. Looks good, closing.
