### ISSUE TITLE
Uninstrument `secondLawScreen.view.panels.rightPanels.targetOrbitPanel`

### ISSUE THREAD

**Issue by arouinfar** [phetsims/keplers-laws#227]
Discovered while writing examples.md for #223 

The Target Orbit feature is only relevant for the first and third laws, but the panel appears in the tree on the Second Law screen:
![image](https://github.com/phetsims/keplers-laws/assets/8419308/b95fbaeb-9c5e-4c06-9bb2-95a105078cbc)

This feature was not designed to be used with the Second Law screen, so let's unintrument `secondLawScreen.view.panels.rightPanels.targetOrbitPanel`.

**Comment by pixelzoom** [comment]
In KeplersLawsPanel.ts, the 3rd argument needs to be conditional, so that it's `Tandem.OPT_OUT` for the Second Law:

```ts
    const targetOrbitPanel = new TargetOrbitPanel( model, topLayer, tandem.createTandem( 'targetOrbitPanel' ) );
```

**Comment by arouinfar** [comment]
Thanks @AgustinVallejo. I'm seeing `targetOrbitPanelVisibleProperty` instrumented for the Second Law screen, so I think you'll need to take care of that too.

**Comment by AgustinVallejo** [comment]
My bad, fixing

**Comment by arouinfar** [comment]
Thanks @AgustinVallejo, looks good on main, closing.
