### ISSUE TITLE
Improve screen icons. 

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/keplers-laws#23]
Now that the icons are for screens and not for scenes, it means that users can see them bigger. I think that is not good their iconic shape for screens, and also Lab needs a better icon.  I am assigning myself for a working on a better design. 

![image](https://user-images.githubusercontent.com/26031501/232922752-22f3b5a0-9e1f-4563-b770-9178e2c5bb27.png)

**Comment by DianaTavares** [comment]
There is the new draft for the icons of this simulation. Please @AgustinVallejo, makes them with code (I take several screenshots of the simulation, then images are not very clean):

![Kepler's Laws-24](https://user-images.githubusercontent.com/26031501/234655137-22c1e618-2a1d-4430-8797-6e6e26625762.png)
![Kepler's Laws-25](https://user-images.githubusercontent.com/26031501/234655139-aefee6e1-7ca9-4cf9-83e6-5dba052a9c4d.png)
![Kepler's Laws-26](https://user-images.githubusercontent.com/26031501/234655141-7fb14588-e343-4aff-8148-9c30ffb8fac0.png)
![Kepler's Laws-27](https://user-images.githubusercontent.com/26031501/234655144-d25c6a07-12cb-410a-a96b-54af8f38627e.png)

**Comment by DianaTavares** [comment]
Use these same icons for the lab screen

**Comment by AgustinVallejo** [comment]
![image](https://github.com/phetsims/keplers-laws/assets/37052186/9af7e871-6d01-4cc1-9423-6515607a5164)
Got it working to this point. However, I might need some assistance on the Law Buttons, which now lost their aspect ratio.

**Comment by DianaTavares** [comment]
I love it!!
