### ISSUE TITLE
Restart button stays enabled

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/keplers-laws#231]
**Test device**
MacBook Air M1 chip

**Operating System**
14.1.2

**Browser**
Safari 17.1.2

**Problem description**
For https://github.com/phetsims/qa/issues/1023, on all screens the Restart button stays enabled after it is pressed.

**Steps to reproduce**
1. On any screen, press Play
2. Press Restart

**Visuals**

https://github.com/phetsims/keplers-laws/assets/87318828/07481bc2-5729-4a54-8b33-586e3f64b08c

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Kepler's Laws‬
URL: https://phet-dev.colorado.edu/html/keplers-laws/1.2.0-dev.7/phet/keplers-laws_all_phet.html
Version: 1.2.0-dev.7 2024-01-09 17:06:22 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.1.2 Safari/605.1.15
Language: en-US
Window: 1357x684
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by AgustinVallejo** [comment]
Thanks @Nancy-Salpepi, assigning back for review!

**Comment by Nancy-Salpepi** [comment]
This looks fixed now on main. Closing!
