### ISSUE TITLE
Extra Sound heard when pressing Restart

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/keplers-laws#232]
**Test device**
MacBook Air M1 chip

**Operating System**
14.1.2

**Browser**
Safari 17.1.2

**Problem description**
For https://github.com/phetsims/qa/issues/1023, on the Second Law screen the crashing bodies sound is heard when pressing Restart. 

**Steps to reproduce**
1. On the Second Law Screen, press play
2. Wait until one period has passed and then press the Restart button

**Visuals**
You might need to raise your volume to hear it.

https://github.com/phetsims/keplers-laws/assets/87318828/cdca4f91-7da6-412d-99e7-6e132dd07381

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Kepler's Laws‬
URL: https://phet-dev.colorado.edu/html/keplers-laws/1.2.0-dev.7/phet/keplers-laws_all_phet.html
Version: 1.2.0-dev.7 2024-01-09 17:06:22 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.1.2 Safari/605.1.15
Language: en-US
Window: 1357x684
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by Nancy-Salpepi** [comment]
I also hear it with the Reset All button

1. Press Play
2. After one period passes, press Pause
3. Press Reset All

**Comment by Nancy-Salpepi** [comment]
Actually, I hear an extra sound on all screens with both the Restart and Reset all buttons.
1. Press play
2. Let the planet travel ~1/2 orbit and then press Pause
3. Press Restart or Reset All

**Comment by AgustinVallejo** [comment]
This is beyond weird, because without a doubt that is the collision sound. However, there's no collisions in Kepler's Laws, furthermore, not even by commenting/removing/changing all the places that sound is referenced in the sim, I just cannot get rid of the sound... Also the fact that it only happens close to the semi-minor axis really confuses me.

**Comment by Nancy-Salpepi** [comment]
@AgustinVallejo the collision sound is heard in this sim when creating an orbital with "the body will crash into the sun..." message 
<img width="559" alt="Screenshot 2024-02-01 at 4 36 15 PM" src="https://github.com/phetsims/keplers-laws/assets/87318828/46b3443e-126f-4117-b9b9-a545e7a286cb">

**Comment by AgustinVallejo** [comment]
Thanks @Nancy-Salpepi!! That's the hint I needed, I was looking in a totally different place. With that insight it was really easy to solve. Assigning back for review

**Comment by Nancy-Salpepi** [comment]
Things sound fine with the Reset All button on main. 
There is still an issue with the Restart button. 
See steps in https://github.com/phetsims/keplers-laws/issues/232#issue-2077875895.

**Comment by AgustinVallejo** [comment]
For including the restart I had to change a bit my approach in solving this, but should be ready now! Thanks

**Comment by Nancy-Salpepi** [comment]
Everthing sounds good now! 👂🏻
