### ISSUE TITLE
Panel size changes as body moves

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/keplers-laws#234]
**Test device**
MacBook Air M1 chip

**Operating System**
14.1.2

**Browser**
Safari 17.1.2

**Problem description**
For https://github.com/phetsims/qa/issues/1023, with some locales (Chinese, Arabic) I noticed that the panel resizes as the values change while the body orbits. This is only seen when "More Orbital Data" is on. 
I don't see this issue in the published version. 

**Steps to reproduce**
Here is an example:
1. Add ?stringTest=X to the url
2. In Preferences turn on "More Orbital Data"
3. On the First Law screen, check "Eccentricity"
4. Press Play

**Visuals**

https://github.com/phetsims/keplers-laws/assets/87318828/ea3564df-88fb-44f2-b8fe-99c9dc888fa2

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Kepler's Laws‬
URL: https://phet-dev.colorado.edu/html/keplers-laws/1.2.0-dev.7/phet/keplers-laws_all_phet.html
Version: 1.2.0-dev.7 2024-01-09 17:06:22 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.1.2 Safari/605.1.15
Language: en-US
Window: 1357x684
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by AgustinVallejo** [comment]
Also, it seems weird that with the string test some numbers turn into X while others do not, should this be reported/fixed?

**Comment by Nancy-Salpepi** [comment]
>Also, it seems weird that with the string test some numbers turn into X while others do not, should this be reported/fixed?

It looks OK to me (but you can ask a dev to be sure). I think numbers followed by units turn into X's because the units are translatable.

**Comment by AgustinVallejo** [comment]
Yup, worked on this yesterday with @jonathanolson and he said it's okay that some things are not X, it really depends on how the text was implemented. Assigning back to you @Nancy-Salpepi, thanks!

**Comment by Nancy-Salpepi** [comment]
This looks good now 🙂
Closing.
