### ISSUE TITLE
Some touch areas overlap

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/keplers-laws#235]
**Test device**
MacBook Air M1 chip

**Operating System**
14.1.2

**Browser**
Safari 17.1.2

**Problem description**
For https://github.com/phetsims/qa/issues/1023, when zoomed in, I can see that the checkboxes overlap slightly. On the Third Law screen, the touch areas for the thumb and the increment/decrement buttons can overlap. 

**Visuals**
<img width="913" alt="Screenshot 2024-01-12 at 4 03 13 PM" src="https://github.com/phetsims/keplers-laws/assets/87318828/9ba973b9-e72a-48d5-8661-71961cf01393">

<img width="285" alt="Screenshot 2024-01-12 at 4 12 55 PM" src="https://github.com/phetsims/keplers-laws/assets/87318828/2783754d-e946-4320-a402-e3c110217ab2">

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Kepler's Laws‬
URL: https://phet-dev.colorado.edu/html/keplers-laws/1.2.0-dev.7/phet/keplers-laws_all_phet.html
Version: 1.2.0-dev.7 2024-01-09 17:06:22 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.1.2 Safari/605.1.15
Language: en-US
Window: 1357x684
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by Nancy-Salpepi** [comment]
Slight overlap on the Second Law screen too:
<img width="594" alt="Screenshot 2024-01-19 at 10 56 31 AM" src="https://github.com/phetsims/keplers-laws/assets/87318828/1ee0aa29-b971-4bc5-b482-11c931f76fb8">

**Comment by AgustinVallejo** [comment]
Assigning back for review

**Comment by Nancy-Salpepi** [comment]
looks good on main. Closing.
