### ISSUE TITLE
PhET-iO API file is out of sync

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/keplers-laws#236]
It looks like many changes were made and `grunt generate-pheti-io-api` was not run.  This is blocking my ability to check-in work for other repos, because git-hooks are failing.

**Comment by pixelzoom** [comment]
@AgustinVallejo See the above commit for the updated API file.  You should inspect this commit carefully to verify that all changes are expected.  

Also... How did these changes get committed without git-hooks failing?

**Comment by pixelzoom** [comment]
Is this problem present in your dev test https://github.com/phetsims/qa/issues/1023?

**Comment by AgustinVallejo** [comment]
Thanks @pixelzoom! I hadn't caught that at all! The dev test is probably also obsolete, how could I check that it's not causing any troubles?

**Comment by pixelzoom** [comment]
I don't know why the was not caught by git-hooks.  It might be https://github.com/phetsims/keplers-laws/issues/237, or there might still be a subset of sims that are tested by githooks.  We'll need to ask @samreid or @zepumph.

I'm guessing that https://github.com/phetsims/keplers-laws/issues/237 is responsible for the lack of automatic API comparison when launching Studio.   If I launch Studio in phetmarks with "Compare with reference API" checked in the Query Parameters column, then it immediately fails.

**Comment by zepumph** [comment]
>I don't know why the API changes were not flagged by git-hooks.

@AgustinVallejo did you commit with git hooks? I believe `keplers-laws` is correctly part of the API hooks, since it is part of `phet-io-api-stable`. The `state-unsupported` piece should not be related to this.

**Comment by AgustinVallejo** [comment]
As far as I'm aware I have git hooks on! I'm not sure why this was slipping through...
