### ISSUE TITLE
Remove keplers-laws from phet-io-state-unsupported

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/keplers-laws#237]
keplers-laws is still listed in perennial/data/phet-io-state-unsupported.   This removes the sim from State Wrapper fuzz testing on CT.  At this point in development (QA dev testing), the sim should definitely not be opting out of State Wrapper fuzz testing.

**Comment by zepumph** [comment]
Weird, looks like keplers-laws was accidentally brought back by @jbphet in https://github.com/phetsims/perennial/commit/f75d55f74c7cd1be5b5a5780736cfb0f0f798440. I believe it was just a stale pull/commit situation, but I just re-removed keplers-laws. I'm surprised that rebase/merging upon next pull/push didn't cause any trouble here. Weird! Anyways. Just noting here for the record, no further steps needed.

**Comment by jbphet** [comment]
Ah, sorry.  I do recall there was some weird merge/rebase issue that come up on that commit.  There must have been two commits very close together and I just blew the merge.  Thanks for fixing @zepumph!
