### ISSUE TITLE
Swept Area Colors are different in launched sim

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/keplers-laws#239]
**Test device**
MacBook Air M1 chip

**Operating System**
14.1.2

**Browser**
Safari 17.1.2

**Problem description**
For https://github.com/phetsims/qa/issues/1023, on the Second Law Screen in the State wrapper:
The colors in the downstream sim don't match those in the upstream sim. Pressing play results in the colors changing to match.

**Steps to reproduce**
1. Set state rate = 0 in the State wrapper
2. Press Play and then after an area has been filled, press Pause
3. Press Set state now --> colors don't match
4. Press Play --> colors match

**Visuals**

<img width="548" alt="Screenshot 2024-01-17 at 2 47 28 PM" src="https://github.com/phetsims/keplers-laws/assets/87318828/5ae57129-9622-4952-a25b-c0919cf1307a">

**Comment by AgustinVallejo** [comment]
Or this:
![image](https://github.com/phetsims/keplers-laws/assets/37052186/03ea2843-e707-41a2-a79b-e126dc20db14)

**Comment by Nancy-Salpepi** [comment]
The color issue has been solved. 
Closing.
