### ISSUE TITLE
Restart button not working correctly in launched sim

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/keplers-laws#240]
**Test device**
MacBook Air M1 chip

**Operating System**
14.1.2

**Browser**
Safari 17.1.2

**Problem description**
For https://github.com/phetsims/qa/issues/1023 I am seeing the same issue as in https://github.com/phetsims/my-solar-system/issues/327, where the restart button in the launched sim resets the planet to the default position rather than the state it was launched in.

**Steps to reproduce**
1. In the state wrapper, set state rate = 0
2. On any Screen, press Play in the upstream sim and then Pause after a second
3. Press Set State Now
4. Press Play in the downstream sim 
5. Press Restart

**Visuals**

https://github.com/phetsims/keplers-laws/assets/87318828/93d7b69b-6e9e-4fb9-8e0b-0abc0233014f

**Comment by Nancy-Salpepi** [comment]
It also changes what areas are shaded. For example, if I had pressed the Erase button prior to launching the sim, pressing Restart results in all the shaded areas being filled. 

https://github.com/phetsims/keplers-laws/assets/87318828/f94475b9-3b40-4cc8-93dc-70ca04f744e5

**Comment by pixelzoom** [comment]
@AgustinVallejo Let me know if you need help with this.

**Comment by AgustinVallejo** [comment]
It was the same fix, so I moved it from MSS into Solar System Common. Assigning back for review, thanks!

**Comment by Nancy-Salpepi** [comment]
Looks good on main.
Closing.
