### ISSUE TITLE
Hint Arrows don't reappear with Reset All

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/keplers-laws#241]
**Test device**
MacBook Air M1 chip

**Operating System**
14.1.2

**Browser**
Safari/chrome

**Problem description**
For https://github.com/phetsims/qa/issues/1023, on all screens the hint arrows around the planet don't reappear after pressing Reset All. 
This don't happen in published. 

**Steps to reproduce**
1. On any screen press Play
2. Press Reset All

**Visuals**

https://github.com/phetsims/keplers-laws/assets/87318828/0c6ce0ce-5610-4f4b-93b4-f6b54bac4591

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Kepler's Laws‬
URL: https://phet-dev.colorado.edu/html/keplers-laws/1.2.0-dev.7/phet/keplers-laws_all_phet.html
Version: 1.2.0-dev.7 2024-01-09 17:06:22 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
Language: en-US
Window: 1384x728
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by AgustinVallejo** [comment]
Assigning back for review

**Comment by Nancy-Salpepi** [comment]
This looks fixed in main. 
I have a related question about the cueing arrows--
They disappear when I press play, change the mass of the star and when I move the planet, but they don't disappear when I press the step forward button (same on published). Is that the desired behavior @AgustinVallejo or should I make a new issue for that?

**Comment by AgustinVallejo** [comment]
We can cover it in this issue. Will do shortly

**Comment by AgustinVallejo** [comment]
Done. Assigning back for review

**Comment by Nancy-Salpepi** [comment]
Everything with the cueing arrows looks good now on main. Closing.
