### ISSUE TITLE
Orbital image increases in size when Standard wrapper is opened

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/keplers-laws#242]
**Test device**
MacBook Air M1 chip

**Operating System**
14.1.2

**Browser**
Safari 17.1.2

**Problem description**
For https://github.com/phetsims/qa/issues/1023, when I launch the Standard wrapper in Studio, the orbital image "grows" when I open the wrapper. 

**Steps to reproduce**
1. In studio, select any screen
2. Press Test (or download file)
3. Open the Standard Wrapper 

**Visuals**

https://github.com/phetsims/keplers-laws/assets/87318828/efdc46c3-9dd0-45c0-b2bb-0261ff9793b3

**Comment by Nancy-Salpepi** [comment]
I also see the image change size if I were to zoom out in studio before launching the sim.
Steps:
1. In studio, on any screen press the Zoom Out button
2. In the Standard Wrapper, press Reset All

https://github.com/phetsims/keplers-laws/assets/87318828/0118d21d-df5f-47f0-8247-a005eb4c7789

**Comment by KatieWoe** [comment]
I saw this as well. Looking at the grid and the measuring tape, the scale doesn't seem altered. I wonder if it has to do with window size.
<img width="957" alt="winsize" src="https://github.com/phetsims/keplers-laws/assets/41024075/7259df91-2fcc-4696-a407-815f6cd26fdb">
<img width="947" alt="winsize2" src="https://github.com/phetsims/keplers-laws/assets/41024075/bed1f589-fbb1-414f-b1de-a9ed9d8d92da">

**Comment by AgustinVallejo** [comment]
Ready for review, assigning back, thanks!

**Comment by Nancy-Salpepi** [comment]
Looks good on main!
Closing.
