### ISSUE TITLE
Stopwatch display size can be larger than stopwatch

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/keplers-laws#243]
**Test device**
MacBook Air M1 chip and iPad

**Operating System**
macOS 14.1.2 and iPadOS 17.2

**Browser**
Chrome and Safari

**Problem description**
For https://github.com/phetsims/qa/issues/1023, the size of the time display on the stopwatch can exceed the size of the stopwatch itself. This is seen when the locale is French but also really easy to see with stringTest=dynamic. 

**Steps to reproduce**
1. Add ?stringTest=dynamic to the end of the url
2. Go to any screen and check the Stopwatch
3. Press the right arrow key once. 

**Visuals**
<img width="359" alt="Screenshot 2024-01-19 at 12 21 10 PM" src="https://github.com/phetsims/keplers-laws/assets/87318828/6967c533-3a8c-4759-accb-a139e1b2e362">

<img width="193" alt="Screenshot 2024-01-19 at 12 20 21 PM" src="https://github.com/phetsims/keplers-laws/assets/87318828/94e0f533-a4c3-4701-8470-f57361e95520">

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: Kepler's LawsKepler's Laws
URL: https://phet-dev.colorado.edu/html/keplers-laws/1.2.0-dev.7/phet/keplers-laws_all_phet.html?stringTest=dynamic
Version: 1.2.0-dev.7 2024-01-09 17:06:22 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
Language: en-US
Window: 1384x728
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by pixelzoom** [comment]
This is probably a problem with StopwatchNode or NumberDisplay (used by StopwatchNode).

@AgustinVallejo Let me know if you need assistance with this.

**Comment by AgustinVallejo** [comment]
Paired with @jonathanolson and @zepumph to solve. Assigning back for review, it should be nice now. Assigning back for review
