### ISSUE TITLE
Unable to set new orbital targets

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/keplers-laws#245]
**Test device**
Samsung and Dell Laptops
**Operating System**
Win 11
**Browser**
Chrome and Firefox
**Problem description**
For https://github.com/phetsims/qa/issues/1023
In studio, whenever I try to set a new target orbit I am met with an error that says it is an invalid JSON value. I have tried entering targets close to the default orbit so I know it should be a valid orbit.
**Steps to reproduce**
1. In studio, go to the element `keplersLaws.firstLawScreen.view.panels.rightPanels.targetOrbitPanel.targetOrbitComboBox.listBox.targetOrbit1Item.visibleProperty` and turn it on
2. Go to the target orbit 1 option in the drop down box of target orbits
3. Go to the element `keplersLaws.global.model.phetioTargetOrbits.targetOrbit1Property`
4. Click Get Value
5. Change the eccentricity to .3 and semi major axis to 1.5.
6. Try to Set value

**Visuals**
![invalidjson2](https://github.com/phetsims/keplers-laws/assets/41024075/aeeec65e-eddf-4b87-8e6f-dab0ff1d9763)
![invalidjson](https://github.com/phetsims/keplers-laws/assets/41024075/791559a7-272b-49c3-bce2-8600a9f55eac)

**Comment by KatieWoe** [comment]
Ok, I think I figured it out! If I use 0.3 instead of .3 it works. This still seems buggy to me.

**Comment by arouinfar** [comment]
@KatieWoe JSON format expects leading zeros on decimals, so I don't believe there is anything we can do here.

**Comment by pixelzoom** [comment]
@AgustinVallejo let me know if you need help with this.

**Comment by AgustinVallejo** [comment]
Closing since there's nothing we can improve on
