### ISSUE TITLE
Graph is buggy with Eraser/Restart buttons

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/keplers-laws#249]
**Test device**
MacBook Air M1 chip

**Operating System**
14.3

**Browser**
Safari 17.3

**Problem description**
For https://github.com/phetsims/qa/issues/1034, on the Third Law screen the appearance of the graph when the Eraser button and Restart button are used is buggy. Sometimes after erasing and then pressing restart, the line in the graph reappears (while other times it doesn't). 
In published, the line in the graph doesn't reappear if the Eraser button had been pressed following the same steps below. 

**Steps to reproduce**
Here is a set of steps I have been able to consistently reproduce this problem with:
1. On the Third Law screen, press Play
2. Increase the Star Mass to 2
3. Press Play
4. Press Erase
5. Press Restart
**it also happens with other masses, but not consistently. 

**Visuals**

https://github.com/phetsims/keplers-laws/assets/87318828/7b3af2c8-2ec9-46ba-be00-da21487ec8d1

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Kepler's Laws‬
URL: https://phet-dev.colorado.edu/html/keplers-laws/1.2.0-rc.1/phet/keplers-laws_all_phet.html
Version: 1.2.0-rc.1 2024-02-02 22:32:44 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.3 Safari/605.1.15
Language: en-US
Window: 1293x711
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by AgustinVallejo** [comment]
Above commit should fix it. Please let me know and mark as cherry pick if done :)

**Comment by Nancy-Salpepi** [comment]
Looks good on main!

**Comment by Nancy-Salpepi** [comment]
Looks good in rc2. Closing!
