### ISSUE TITLE
Disable Restart when new state is created

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/keplers-laws#250]
**Test device**
MacBook Air M1 chip

**Operating System**
14.3

**Browser**
Safari 17.3

**Problem description**
For https://github.com/phetsims/qa/issues/1034, pressing the Restart button after setting a new state doesn't do anything. Wondering if maybe the Restart button should be disabled when a new state is created?

**Steps to reproduce**
1. On any screen, press Play
2. Grab the body, velocity vector, or if on the Third Law screen change the Star mass. (you can also press Pause before this step)
3. Press the restart button

**Visuals**

https://github.com/phetsims/keplers-laws/assets/87318828/41c32fb4-3c75-4639-9b35-5db12b73c9c5

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Kepler's Laws‬
URL: https://phet-dev.colorado.edu/html/keplers-laws/1.2.0-rc.1/phet/keplers-laws_all_phet.html
Version: 1.2.0-rc.1 2024-02-02 22:32:44 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.3 Safari/605.1.15
Language: en-US
Window: 1293x711
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by AgustinVallejo** [comment]
This is done, can you double check? Mark as cherrry-pick if done :)

**Comment by Nancy-Salpepi** [comment]
this is working nicely!
