### ISSUE TITLE
Values change when (un)checking Always Circular checkbox

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/keplers-laws#252]
**Test device**
MacBook Air M1 chip

**Operating System**
14.3

**Browser**
Safari 17.3 and Chome

**Problem description**
For https://github.com/phetsims/qa/issues/1034, on the First Law and Third Law Screens the values change if the Always Circular Checkbox is checked and unchecked while the sim is playing. 
This is also seen in published. 

**Steps to reproduce**
1. On the First Law screen, check the Eccentricity checkbox
2. Press Play
3. Repeatedly check and uncheck the Always Circular checkbox
4. The change is even more obvious with smaller orbits

**Visuals**

https://github.com/phetsims/keplers-laws/assets/87318828/958b1e88-649f-4359-b0ff-644d32ef9d82

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Kepler's Laws‬
URL: https://phet-dev.colorado.edu/html/keplers-laws/1.2.0-rc.1/phet/keplers-laws_all_phet.html
Version: 1.2.0-rc.1 2024-02-02 22:32:44 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36
Language: en-US
Window: 1394x708
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by AgustinVallejo** [comment]
Are you able to reproduce this in main? I believe this was potentially fixed along https://github.com/phetsims/keplers-laws/issues/248 and I'm not currently being able to reproduce

**Comment by Nancy-Salpepi** [comment]
I can't reproduce it on main either.

**Comment by AgustinVallejo** [comment]
Closing, cherry-picking the other issue should fix this.

**Comment by Nancy-Salpepi** [comment]
Reopening.
This issue looks good on main but not in rc.2

**Comment by AgustinVallejo** [comment]
Darn, I missed #248 in the cherry picks. Should be done for rc.3 as well as QA credits.

**Comment by Nancy-Salpepi** [comment]
This looks good in rc.3 
Closing!
