### ISSUE TITLE
highlights disappear after tabbing to radio buttons

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/keplers-laws#253]
**Test device**
MacBook Air M1 chip

**Operating System**
14.3

**Browser**
Chrome

**Problem description**
For https://github.com/phetsims/qa/issues/1034, on all screens with mac + chrome:
Keyboard focus disappears when tabbing though the controls while zoomed in once I reach the control _after_ a radio button group. It reappears and disappears sporadically as I continue to tab. I don't see this issue in Kepler's Laws 1.2.0-dev.7. I don't see this issue with safari.

**Steps to reproduce**
1. Go to the First Law screen and zoom in using `command` + `+`.
2. Tab though the controls--focus should be lost when focus moves from the Speed radio buttons to the Zoom buttons
3. If it doesn't happen the first time, change the speed using keyboard nav and then continue to tab.

**Visuals**

https://github.com/phetsims/keplers-laws/assets/87318828/88e0cbf3-a44b-42c8-9f12-6ed330e244b4

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Kepler's Laws‬
URL: https://phet-dev.colorado.edu/html/keplers-laws/1.2.0-rc.1/phet/keplers-laws_all_phet.html
Version: 1.2.0-rc.1 2024-02-02 22:32:44 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36
Language: en-US
Window: 1394x708
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by Nancy-Salpepi** [comment]
I had originally thought this issue was related to https://github.com/phetsims/scenery/issues/1604 and reported it there. 
Here are @zepumph's comments from that issue:
> I can consistently reproduce this by zooming in on the third law screen, then tabbing in a way that the next focusable is off my current view. For example, tabbing between the graph accordionBox title and the stopwatch checkbox. I am listening to the pdomHighlgihtsVisibleProperty and its value isn't changing, so I'll keep taking a look. Thanks for the report @Nancy-Salpepi.

> @Nancy-Salpepi can you please create a new issue. I too cannot reproduce in the older dev version, but I also CAN reproduce when I revert the above commit (https://github.com/phetsims/scenery/commit/9fbeb1d247e88f842541d0420e780bfa2937af25) in my local copy, so I don't believe this is related to this issue (at least not closely).

**Comment by zepumph** [comment]
Looks like good progress in https://github.com/phetsims/scenery/issues/1605. I'll unassign this guy until we have a common solution settled.

**Comment by Nancy-Salpepi** [comment]
This is not fixed in rc.2, but works well on main.

**Comment by Nancy-Salpepi** [comment]
This issue if fixed in rc.3
I do see https://github.com/phetsims/scenery/issues/1507, but that is a separate common code issue. 

Closing
