### ISSUE TITLE
isActiveProperty should not be featured

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/keplers-laws#254]
**Test device**
MacBook Air M1 chip

**Operating System**
14.3

**Browser**
Safari 17.3

**Problem description**
For https://github.com/phetsims/qa/issues/1034, please unfeature the `isActiveProperty` for both bodies on all screens. 
I confirmed this with @arouinfar over slack:
> Oh, good find. I think isActiveProperty is likely a necessary for the implementation, but it doesn’t make sense to feature it in the context of Kepler’s Laws, which always has 2 active bodies that cannot crash or escape.

<img width="757" alt="Screenshot 2024-02-06 at 2 15 38 PM" src="https://github.com/phetsims/keplers-laws/assets/87318828/af970bf8-4444-49a6-ac65-cebfe93bf231">

**Comment by AgustinVallejo** [comment]
Assigning back for review

**Comment by Nancy-Salpepi** [comment]
Looks good on Main.

**Comment by Nancy-Salpepi** [comment]
Looks good in rc.2
Closing!
