### ISSUE TITLE
planet.massProperty should be Read Only

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/keplers-laws#255]
**Test device**
MacBook Air M1 chip

**Operating System**
14.3

**Browser**
Safari 17.3

**Problem description**
For https://github.com/phetsims/qa/issues/1034, the acceptable range for the planet.massProperty is only 1 value (50). Discussed with @arouinfar over slack and it makes more sense for this property to be Read Only. 

**Visuals**
<img width="1258" alt="Screenshot 2024-02-06 at 3 02 15 PM" src="https://github.com/phetsims/keplers-laws/assets/87318828/e20fbeb8-3582-46de-921c-7c6110557d52">

**Comment by AgustinVallejo** [comment]
I believe the current implementation of `BodyInfo` doesn't allow to pass options (such as `phetioReadonly: true`) into those individual properties. If I recall correctly that's why we changed the range to [50,50]. Could you chime in, @pixelzoom?

**Comment by AgustinVallejo** [comment]
Good changes! Thanks @pixelzoom. Assigning back to QA to double check and mark as ready to cherry pick

**Comment by Nancy-Salpepi** [comment]
Looks good!

**Comment by Nancy-Salpepi** [comment]
looks good in rc.2
