### ISSUE TITLE
Font issues in Kepler's Laws activities

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/keplers-laws#256]
For the activities posted on the website, the Learning goals and/or the link to the sim aren't displaying correctly:

<img width="666" alt="Screenshot 2024-02-06 at 3 12 14 PM" src="https://github.com/phetsims/keplers-laws/assets/87318828/393eb04f-10a3-46ae-b331-bef109d795e2">

<img width="666" alt="Screenshot 2024-02-06 at 3 23 21 PM" src="https://github.com/phetsims/keplers-laws/assets/87318828/2767c166-aad4-4c7c-9c1f-db46450fadea">

**Comment by Nancy-Salpepi** [comment]
While you are making the above changes....you might want to delete the `" ` at the end of the title for the First Law activity. 
Also, I would remove the  ( ) after "context" and "PhET sim"
<img width="666" alt="Screenshot 2024-02-06 at 3 25 18 PM" src="https://github.com/phetsims/keplers-laws/assets/87318828/9abfa3f0-2f13-490d-aefc-e9029ec4b63d">

I would be happy to take a closer look at the activities if you want. LMK!

**Comment by DianaTavares** [comment]
The activities look good from my end:

![image](https://github.com/phetsims/keplers-laws/assets/26031501/f2a935a9-abf4-4980-8324-d799b60411de)

I will submit PDF files, in that case users can download them without affecting the view. 

Would be nice to have a review of the activity! Yes, please, take a closer look! 

LMK if now with the PDFs you can see the activities. I Already submitted them on the website, but take a while to be visible for everybody.

**Comment by Nancy-Salpepi** [comment]
PDFs look good and now so do the Word versions of the activities. I'm not sure why that was happening yesterday. 
I will give the activities a review but will close this issue.
