### ISSUE TITLE
Mars marker on graph is initially obscured 

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/keplers-laws#262]
**Test device**
MacBook Air M1 chip

**Operating System**
14.3

**Browser**
Safari 17.3

**Problem description**
For https://github.com/phetsims/qa/issues/1034, the Mars "dot" is initially hidden by the pink dot. 

<img width="1347" alt="Screenshot 2024-02-12 at 11 32 14 AM" src="https://github.com/phetsims/keplers-laws/assets/87318828/321a316b-738f-4330-9cad-ab4f857953cb">

**Comment by Nancy-Salpepi** [comment]
it looks good when the 2 dots overlap but when they don't, the gray dot seems huge. 
@arouinfar @AgustinVallejo do you think it looks ok?
<img width="334" alt="Screenshot 2024-02-12 at 1 11 50 PM" src="https://github.com/phetsims/keplers-laws/assets/87318828/f0a1d01f-b800-4402-8a5c-c23345f3b5ba">
<img width="334" alt="Screenshot 2024-02-12 at 1 12 18 PM" src="https://github.com/phetsims/keplers-laws/assets/87318828/2e17370f-d976-40fb-94de-e0be4c5a19aa">

**Comment by AgustinVallejo** [comment]
@arouinfar answered in slack to scale up the grey marker _only_ when it's obscured by the other one.

**Comment by AgustinVallejo** [comment]
Above commit addresses that change, please review and mark for cherry picking :)

**Comment by Nancy-Salpepi** [comment]
The gray dot get larger as soon as there is any overlap. Just wanted to confirm with @arouinfar that this is working as desired.

https://github.com/phetsims/keplers-laws/assets/87318828/4521becc-d46d-43e0-8f93-3402317d77d6

**Comment by arouinfar** [comment]
Thanks for checking @Nancy-Salpepi.

@AgustinVallejo I think the behavior in Nancy's video is acceptable, but it would look nicer if the gray dot grows only when there is perfect overlap.

**Comment by AgustinVallejo** [comment]
Assigning back for review

**Comment by Nancy-Salpepi** [comment]
Looks much better to me! The gray dot is still enlarged over a range of values but that range is much smaller.

**Comment by Nancy-Salpepi** [comment]
looks good in rc.2
