### ISSUE TITLE
Rendering order and location of cueing arrows different than published

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/keplers-laws#263]
**Test device**
MacBook Air M1 chip and Chromebook

**Operating System**
macOS 14.3

**Browser**
Safari  and Chrome

**Problem description**
For https://github.com/phetsims/qa/issues/1034, I see 2 differences between 1.2.0-rc.1 and published: the grid lines seem to now be in front of the semiaxes. Also the cueing arrows are further from the planet than in published. 

**Visuals**
rc: 
<img width="497" alt="Screenshot 2024-02-12 at 2 18 39 PM" src="https://github.com/phetsims/keplers-laws/assets/87318828/5231473d-1aff-4c98-95ae-00fbe1bb6023">

published:
<img width="497" alt="Screenshot 2024-02-12 at 2 18 51 PM" src="https://github.com/phetsims/keplers-laws/assets/87318828/a905f234-c182-4aa6-beec-985570002fd9">

**Comment by AgustinVallejo** [comment]
Fixed rendering order and cueing arrows. Please review and mark for cherry picking :)

**Comment by Nancy-Salpepi** [comment]
Cueing arrows look good on main

**Comment by Nancy-Salpepi** [comment]
Now that you made the rendering order change I can see that it wasn't actually the order that was different....it looks like the grid lines where thinner in published. I think the current look on main looks OK, but wanted to double check with @AgustinVallejo and @arouinfar.

RC:
<img width="1023" alt="Screenshot 2024-02-13 at 1 30 44 PM" src="https://github.com/phetsims/keplers-laws/assets/87318828/932c5083-d9c4-4d08-8307-4e3e0d5e83e2">

Published:
<img width="1023" alt="Screenshot 2024-02-13 at 1 31 05 PM" src="https://github.com/phetsims/keplers-laws/assets/87318828/73499bf2-6bcc-4bc1-9ef1-df50e784a4c2">

Main:
<img width="1023" alt="Screenshot 2024-02-13 at 1 31 27 PM" src="https://github.com/phetsims/keplers-laws/assets/87318828/7287098b-bd18-4de9-9cd8-2103872c9a4f">

**Comment by AgustinVallejo** [comment]
Reverting the grid change. According to @arouinfar, grid should always be on top.

**Comment by Nancy-Salpepi** [comment]
Change has been reverted. 
Cueing arrows ready to cherry pick.

**Comment by Nancy-Salpepi** [comment]
Cueing arrows look good.
