### ISSUE TITLE
Display the relationship of the strings and a only when semiaxes is active. 

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/keplers-laws#28]
We know that usually they interact with the controls from top to bottom. Then, in the first screen, an user (new in this topic) will interact with "strings" first, and the sim is going to display an "`a`"  in the top representation that is not visible in the ellipse:

![image](https://github.com/phetsims/keplers-laws/assets/26031501/3cc85b14-c6cd-4760-abac-457598beb75e)

I suggest that this relationship between `a` and the string is only visible when the Strings and semiaxes are active at the same time, other way, the strings only present d1 and d2 changing length, and 'a' only displays the 'a' in the ellipse

@arouinfar agree with this suggestion.

**Comment by AgustinVallejo** [comment]
This is ready for review!

**Comment by DianaTavares** [comment]
excelent!
