### ISSUE TITLE
Reduce the blank space in the eccentricity fraction 

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/keplers-laws#30]
I know that you asked me about this before @AgustinVallejo, but now it is disturbing me the space between the = and the fraction:

 ![image](https://github.com/phetsims/keplers-laws/assets/26031501/d7f445d7-e35e-4422-9184-5a46c8c94170)

can you make it smaller (same space between the word Eccentricity and the fraction)?

**Comment by AgustinVallejo** [comment]
Done!

**Comment by DianaTavares** [comment]
perfect!
