### ISSUE TITLE
Alignment of the icons in the controls panels 

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/keplers-laws#31]
- [x]  Align all the icons to the right:

![image](https://github.com/phetsims/keplers-laws/assets/26031501/7fab0e0b-a7fb-42e3-aa5c-20e3c048f19a)

- [x] Reduce the length of the vector icons to half (this will give mores space for translation): 

![image](https://github.com/phetsims/keplers-laws/assets/26031501/f51fd08a-e328-413b-a0f5-bc932a6cc287)

**Comment by AgustinVallejo** [comment]
Regarding the second item, I think arrows are the same size as in MSS, its just that text in MSS occupies more space of the panel and it stretches. We can also let this one stretch for translations...

Also, pushed a change for the first item, let me know what you think.

**Comment by DianaTavares** [comment]
perfect!
