### ISSUE TITLE
Testing stringTest=long display panel with not restrictions and words that are not strings

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/keplers-laws#32]
This happens with stringTest=long:

![image](https://github.com/phetsims/keplers-laws/assets/26031501/5bed0a6d-fad4-40cb-8ce9-618f3e6ff450)

- [x] the left panels (like eccentricity in this case) just grows out without not restriction about the size. The same happens in all left panels of the sim. 
- [x] all the planes and stars in the eccentricity scale are not long, then probably they are not in the strings list, and that is a problem for translations. 

- [x] String representation just gets very buggy:
![image](https://github.com/phetsims/keplers-laws/assets/26031501/ec4993f5-3292-4292-b41a-db78eb8cbab9)

- [x] Area readout don't present a change. No sure if that means something related to the translation of AU2
![image](https://github.com/phetsims/keplers-laws/assets/26031501/7739aa3f-787c-4844-bd34-744fa1a259ac)

- [x] T change, but not t^2 and t^3 on the third screen:
![image](https://github.com/phetsims/keplers-laws/assets/26031501/3e125e92-6438-4a8b-a9e7-2ead848413d8)

**Comment by AgustinVallejo** [comment]
@chrisklus hello!

**Comment by AgustinVallejo** [comment]
Added maxWidth to most sim elements. However, I would appreciate help from another dev to make sure the behavior is the desired one, as well as reviewing the remaining items since I wouldn't be very sure as to how to implement them.
