### ISSUE TITLE
Speed readout gets behind the vectors in some cases 

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/keplers-laws#33]
The speed readout is always below the planet, and with not “more data” panel, I'm imaging that this can be a problem for experiments where users need to put the velocity to a specific value and direction, and the only way is by dragging the velocity vector, and for pointing down, the vector covers the speed readout:

![image](https://github.com/phetsims/keplers-laws/assets/26031501/daaaeb24-c0f9-453e-90e7-6095853b8965)

Probably we can do something like in Vectors addition, there the label changes form up to down when the vector moves:
![image](https://github.com/phetsims/keplers-laws/assets/26031501/9a0186b1-a1c4-4558-83e7-53dec7630d3b)

![image](https://github.com/phetsims/keplers-laws/assets/26031501/1a68cccc-6a6c-4e24-a982-7e549fde5cd8)

**Comment by AgustinVallejo** [comment]
This will also affect My Solar System but I think it's beneficial to both sims. Pushing a change. Please review and let me know what you think!

**Comment by DianaTavares** [comment]
It is working!!!
