### ISSUE TITLE
Strange behavior in the starting movement of the planet in big orbits 

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/keplers-laws#34]
This doesn't happen frequently, and I am not sure what triggers because it sometimes happens with small orbits (but is harder to reproduce) and with big orbit is more common that when I click play, the planet movers to another position of the orbit and then star to moves, like in the giff: 
![Play](https://github.com/phetsims/keplers-laws/assets/26031501/20a35d84-81be-4f5f-84db-e74b6b500475)

**Comment by AgustinVallejo** [comment]
Thanks!! There are still some edge cases on the orbit calculator and I'm having trouble reproducing them all, let's hope this gets us closer.

**Comment by AgustinVallejo** [comment]
This should now be corrected
