### ISSUE TITLE
Restring that the planet can be dragged over the panels 

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/keplers-laws#35]
It is supper easy to lose the plant if this can be dragged behind the panels. not to allow that.

**Comment by jonathanolson** [comment]
Implemented above, can you see how this looks?

**Comment by AgustinVallejo** [comment]
Also, we should discuss about this zone of the screen:
![image](https://github.com/phetsims/keplers-laws/assets/37052186/848f5200-acd2-447a-9491-0851a78238a7)
When accordion is turned off, you can drag the planet under it, open it, and lose the planet... Is this desired behaviour? Should we leave the open-accordion space outside of drag bounds?

**Comment by AgustinVallejo** [comment]
![image](https://github.com/phetsims/keplers-laws/assets/37052186/f05a2079-a297-4ec0-b2cc-82e89e6bcd83)
We finally opted in favour of this approach. Closing.
