### ISSUE TITLE
The measuring tape can be dragged in all the play area 

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/keplers-laws#36]
It is like a restriction all the corners of the sim that not allow the metric tape to go to all the play area:
![messuring](https://github.com/phetsims/keplers-laws/assets/26031501/bec9a29d-5067-41ae-a079-f1b6a57df290)

**Comment by jonathanolson** [comment]
Reduced the offset from the edge of the screen for the measuring tape drag bounds. This allows the tip to go closer to the edge of the screen, however it also allows the measuring tape to mostly go off of the screen:

<img width="125" alt="image" src="https://github.com/phetsims/keplers-laws/assets/480878/2fabd3fc-29fb-47b8-82da-2612249fcbc1">

Is this behavior acceptable, or is something else desired?

**Comment by DianaTavares** [comment]
That behavior is acceptable! Looks wonderful!
