### ISSUE TITLE
Improve the position of the area labels on the second screen 

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/keplers-laws#37]
- [ ] the suggestion was that for big areas the label could be placed inside the orbit, to allow to see the numbers in big orbits:

![image](https://github.com/phetsims/keplers-laws/assets/26031501/645f2463-8e64-4e9c-bb04-273c4c2270bf)

For medium and small orbits, are ok to have the labels outside the orbit:
![image](https://github.com/phetsims/keplers-laws/assets/26031501/9e63baa1-6bbc-46f3-8507-4272214be475)

- [ ] but in some small orbits, the labels overlap with the orbit. This need to be solved. 

![image](https://github.com/phetsims/keplers-laws/assets/26031501/a95da7a9-af20-459e-b8e3-eaecbf057a20)

**Comment by AgustinVallejo** [comment]
Pushed a commit that handles as you asked, please review and let me know what you think!

**Comment by DianaTavares** [comment]
When the orbit is small, the labels still going inside the orbit:
![image](https://github.com/phetsims/keplers-laws/assets/26031501/a4cf0fc3-1d28-4e2e-9fdd-ff5c8a217335)

and when it is big, still the labels being out: 
![image](https://github.com/phetsims/keplers-laws/assets/26031501/5c6157d3-f9e0-4ddf-bccb-3ac9f33c4d63)

**Comment by DianaTavares** [comment]
Better!!
but now the labels overlap sometime when they are inside the orbit:
![image](https://github.com/phetsims/keplers-laws/assets/26031501/1e9cafa5-6281-4c1a-b111-56b1f84c9e0d)


and sometimes we have something like this: 
![image](https://github.com/phetsims/keplers-laws/assets/26031501/d53c5de3-8a62-40c1-9fed-b3ef7d58475c)

Also, can be problematic if some labels overlap with more of one area. For example, the labels close to the sun are half in one area and half in the other area:

![image](https://github.com/phetsims/keplers-laws/assets/26031501/0ad623e4-8f98-4be7-8ebb-e3bb1a473c4e)


I suggest making the change of the labels between inside to outside in bigger orbits. Something like this can be the smaller orbit with the labels inside:
![image](https://github.com/phetsims/keplers-laws/assets/26031501/a524a6fd-c0f8-4411-aa32-19304b3a2f7a)

 
Is there a way to place better the labels when they are inside? There is space for having each label just in its area with an  adjustment a little more up for some labels, and to the right for other labels. It is possible to do this dynamically and improve it? 

![image](https://github.com/phetsims/keplers-laws/assets/26031501/89a52e62-c6cb-464e-bc46-daa92fc1a2bb)

**Comment by DianaTavares** [comment]
Looks good!
