### ISSUE TITLE
Improve the contrast of the areas in the second screen

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/keplers-laws#38]
Dynamic changes in the colors of the areas is not working because the contrast still not being good:

![image](https://github.com/phetsims/keplers-laws/assets/26031501/d2c5a7a7-f846-40fd-a801-d128de8ece63)
![image](https://github.com/phetsims/keplers-laws/assets/26031501/3dd2db69-95de-46e6-89cc-1cdde2f20dec)

I suggest using these colors: 
![image](https://github.com/phetsims/keplers-laws/assets/26031501/3bd23857-2c2d-439e-bca4-23e0d1edc7ef)
 `#6D266C`
`#96009A`
`#C906C8`
`#FF00FF`
`#FF4DFF`
`#FF8AFF`

They are not gradients of the same color, bur they are similar for the good-looking of the sim, and they same time different enough to distinguish them. 

@arouinfar, comments about the colors suggested?

**Comment by DianaTavares** [comment]
Better!!
But I'm still finding strange behaviors: 

1. Sometimes all the colors just vanish. It happens when one cycle is complete. I find it strange because still color there, we can see like a ghost, and the area numbers are there when the checkbox is active. I think that the color behavior needs to be all the time constant while is play active.  Always filling with the same colors and maintain the other areas. 

![image](https://github.com/phetsims/keplers-laws/assets/26031501/4e5985ff-d443-4349-b6d8-e46005f80e23)

2. the idea is to have these colors as contrast:
![image](https://github.com/phetsims/keplers-laws/assets/26031501/690b257d-93f8-413f-8c7f-b1db4fd8be54)

but it is like jumping to the last colors, and look the same the last three colors
![image](https://github.com/phetsims/keplers-laws/assets/26031501/8eb5c01a-c6de-404b-b268-537c7edc6010)3. 

3. I really would like to see all the orbit with color, but when the planet starts the last area, it is already invisible the first area:
![image](https://github.com/phetsims/keplers-laws/assets/26031501/a7d5743d-ee47-4241-82a7-35498e60fbf1)

4. In my opinion, I don't like this changing of color of the past areas. I find it distracting because I think that the attention of the student needs to be in the new area filling. With this change of color in the other areas, is several dynamic changes in the simulation. What do you think @arouinfar?

![area](https://github.com/phetsims/keplers-laws/assets/26031501/06380d03-8c01-4fcb-b8b8-c1e2fdaa54b0)

**Comment by arouinfar** [comment]
I completely agree @DianaTavares. 

Here's another example of how rapidly the colors can change, occasionally creating ghost sections.

https://github.com/phetsims/keplers-laws/assets/8419308/8146e71b-9347-4356-8a93-cef774bd9ff6

I would prefer a static set of colors, but the ones you suggested in https://github.com/phetsims/keplers-laws/issues/38#issue-1706452016 can still have some contrast issues with the black background. I can play a bit more with the colors in Illustrator and use a contrast checker to find some alternatives.

**Comment by DianaTavares** [comment]
We decided at today's design meeting that we are going to use solid colors for the area (not shadows or gradients). 

The colors elected are:

`#80007F`
`#A400A4`
`#C800C8`
`#FF24FF`
`#FF6DFF`
`#FF92FF`

The graphs can include stokes for better contrast with the background. These colors will be used for the dark and projector view.
