### ISSUE TITLE
New position of the play control

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/keplers-laws#49]
The play control now has a new position in the center-bottom of the page. All the right panels move up:

First Screen
![image](https://github.com/phetsims/keplers-laws/assets/26031501/491e3df1-5039-42c1-9436-787b6d13803f)

Second Screen
![image](https://github.com/phetsims/keplers-laws/assets/26031501/d457302b-ed17-440c-bfbe-e0c89688e41e)

Third Screen
![image](https://github.com/phetsims/keplers-laws/assets/26031501/3564b825-26b7-4410-a252-cf1fc10bf241)

Four Screen
![image](https://github.com/phetsims/keplers-laws/assets/26031501/eda21ef3-8f89-4df1-b95a-292c258a47dc)

**Comment by AgustinVallejo** [comment]
This is now implemented
