### ISSUE TITLE
Simulation with 4 screens  

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/keplers-laws#5]
Kepler is going to have 4 screens:

- First Law:

![image](https://user-images.githubusercontent.com/26031501/229954035-8ee1546e-82da-44c6-9e80-f5694abb122e.png)

- Second Law
![image](https://user-images.githubusercontent.com/26031501/229954080-7936f79b-32bc-4393-9723-20086b23b5c6.png)

- Third Law
![image](https://user-images.githubusercontent.com/26031501/229954118-ff4f64c4-40ec-4ddb-b792-6b96c176bdf7.png)

- Lab 
![image](https://user-images.githubusercontent.com/26031501/229954309-6b1cdb77-e9dc-4133-9c7e-932914262cc8.png)

**Comment by jonathanolson** [comment]
Implemented above, @DianaTavares can you see how it looks?

**Comment by DianaTavares** [comment]
I am doing “pull” in the phettest, but I don't get a sim updated. I'm still visualizing only one screen

**Comment by AgustinVallejo** [comment]
Maybe phettest is a bit behind, it's showing for me on local
![image](https://user-images.githubusercontent.com/37052186/232132111-780ec349-66a0-42df-bc67-31ba7ff0335b.png)
