### ISSUE TITLE
Add the “Target Orbit Control” 

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/keplers-laws#50]
This control has the functionality of drawing the orbit of the planet selected in the play area with the goal of motivating interaction with the sim: 
![image](https://github.com/phetsims/keplers-laws/assets/26031501/d4083c0e-7328-4c46-ac91-5472278f7006)

When a planet is selected, the text changes to green, to march the color of the orbit drawn in the play area:

![image](https://github.com/phetsims/keplers-laws/assets/26031501/6263d411-b6f4-4db3-9887-371a0ef9b4b7)

I found these values in internet (I ask chat GPT) but please review them: 
![image](https://github.com/phetsims/keplers-laws/assets/26031501/c5d7ba7a-56d4-428b-aaf9-7f235d0226f4)

This control is going to appear only in the first and third law screens/scenes. 

In the case of third and lab screens, the selection of the control will change to None and be disabled when the Star Mass is different from “Our Sun”:

![image](https://github.com/phetsims/keplers-laws/assets/26031501/47a25cbd-427e-4ecf-af3b-dd60878fbbde)

If the user returns the slider to “Our Sun” value, the control is available again, but maintains its None option. 

In the third screen, the "a vs T" graph will display a green dot when a planet is selected in the Target Orbit control. 

![image](https://github.com/phetsims/keplers-laws/assets/26031501/12ded7fb-9d8b-4373-9d9f-008289332bdc)

**Comment by AgustinVallejo** [comment]
May I suggest a different color for the target orbit instead of that green? Maybe a color related to each of the planets, or just any other color. Not a big fan of that dark green to be honest.

**Comment by DianaTavares** [comment]
I like the idea of something related to each planet, just think of the colorblindness test. I use green because it is the one used in My solar system for the 4º body. I can try something like this: 
Mercury – Grey.
Venus – Brown and grey.
Earth – Blue, brown green and white.
Mars – Red, brown and tan.
Jupiter – Brown, orange and tan, with white cloud stripes.

Also, in Slack, we decided to put the Target Orbit control at the top of the panel.

**Comment by DianaTavares** [comment]
![image](https://github.com/phetsims/keplers-laws/assets/26031501/0c09d3f0-9066-4ce4-a310-76cee48b50cf)

**Comment by AgustinVallejo** [comment]
This is done, assigning back for review. Please double check Jupiter's orbit, as I find it particularly hard to achieve because of the sensitivity of the orbit to speed changes at that scale, so it's almost impossible to see the whole orbit and adjust the velocity accordingly to get the right one.

I might even suggest to leave Jupiter out and only use the inner solar system (up to Mars). That way we can also stop needing the zoom buttons.

**Comment by DianaTavares** [comment]
We need to zoom with Jupiter or without Jupiter.

I tried all of them, and it was not super hard to make Jupiter:

![image](https://github.com/phetsims/keplers-laws/assets/26031501/37902618-2946-4836-8014-baccd4336308)


But It is hard to know whether you get it or not. I think we need a kind of animation. I was thinking in:
 1) If eccentricity is open, that the pink readout changes to the color of the target orbit, and probably also the a, b and c readouts. In that way, we bring the attention to the values of that special orbit.
2) Additional, a kind of animation like confetti that fades, and the trajectory line changes to the color of the target orbit, as the stroke is bigger. 

About the difficulty of matching the orbit with the target, can it be a little sticky? When the user drags the planet close to the target orbit, the sim helps to match it. The same with the velocity.

**Comment by DianaTavares** [comment]
The dot of the target orbit in the "a vs t" graph is not implemented yet:

![image](https://github.com/phetsims/keplers-laws/assets/26031501/9bfe3810-ac51-4ec7-b5c1-5f8aad4397f4)

**Comment by DianaTavares** [comment]
- [ ] Also, when I restart the simulation with the orange button, the target orbit doesn't return to its default state (None)

**Comment by DianaTavares** [comment]
Working super well!! Only need the little icon in the control
![image](https://github.com/phetsims/keplers-laws/assets/26031501/f7428c84-4a2d-41dd-9754-549f9e1c0f12)
