### ISSUE TITLE
Improvements in the Area values control, and add time values control in second law screen. 

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/keplers-laws#53]
We are adding a Time Values checkbox in the second law screen:

![image](https://github.com/phetsims/keplers-laws/assets/26031501/d48c3901-4f90-4501-97f7-7c9610507f14)

When the Values controls: Area and/or Time, are selected, the labels are going to appear in the play area, even when their value is zero.
![image](https://github.com/phetsims/keplers-laws/assets/26031501/d3c1e639-0fed-45be-9785-fbdc3b89c289)

To differentiate between the labels, the time has the blue background shown in the screenshot.

**Comment by DianaTavares** [comment]
I don't like how it looks centered: 
![image](https://github.com/phetsims/keplers-laws/assets/26031501/72ac15d3-bf0c-4c5f-a992-62c884a51e92)

**Comment by DianaTavares** [comment]
Also, in the last alternative input meeting, we decided:

- [ ]  to show the graph always fill. 
- [ ] When the user clicks play, the area where the planet is, is going to disappear and start to fill according to its movement. 
- [ ] The Swept Area graph will be open by default, with an eraser button that will delete the area in the graph and in the orbit. 

![image](https://github.com/phetsims/keplers-laws/assets/26031501/13d60244-c631-4420-b4cd-a114d467777e)

**Comment by AgustinVallejo** [comment]
Added horizontal grid lines. I think overall this feature is complete.

Some string are not properties yet, but that's covered in here: https://github.com/phetsims/keplers-laws/issues/32.

Assigning as ready for review.

**Comment by DianaTavares** [comment]
I like the behavior of the readouts of time and area. But the grid lines look funny. Probably no show the small ones when the graph has over 2 bolder grid lines?

![image](https://github.com/phetsims/keplers-laws/assets/26031501/fa0065b0-6022-4c7c-bc7b-ff0dd7b7f8f5)

And I find strange that the graph still active (that you can continue moving the grid lines), when is a not allowed orbit

![image](https://github.com/phetsims/keplers-laws/assets/26031501/33272423-3eb4-4f88-bd13-f2c9f671171e)

I think that in this last scenario, the graph should get inactive (like gray and not changing).

But not 100% sure about this. @arouinfar, @ariel-phet and/or @kathy-phet, can you review the behavior of the area's graph and share your opinion?

**Comment by AgustinVallejo** [comment]
1. I can remove the small grid lines easily, but keep in mind that the smaller ones allow you to properly measure yourself the Area value. i.e. 5.1 AU^2 can be easily read on the chart. Without the lines you would read 5.something.

2. Regarding the last item, the scale of the graph updates with the size of the orbit. When the orbit will crash, the sim state is set to invalid orbit, but you can still change the shape, thus affecting the graph. Let me know if you desire a different behavior.

**Comment by DianaTavares** [comment]
I don't think any user is going to use the graph for a deep measure of the area. The horizontal lines are to reinforce that the height of the bars is the sames. 

I think that with the elimination of the thin horizontal lines the graph will stop being so distracting when there are no values, and possibly it is not necessary to attend to point 2. It only seemed to me a very dynamic graph with lines appearing and disappearing, and have noting to show anything, since it was a situation doesn't not generate orbits.
