### ISSUE TITLE
Add zoom button

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/keplers-laws#55]
In all screens, vertically, close to the right panel. 

![image](https://github.com/phetsims/keplers-laws/assets/26031501/3b75215d-d301-4d03-ac03-291ec40ada6c)

The zoom in by default is inactive, and the sim will have only one zoom out that is twice the size of the play area.

**Comment by AgustinVallejo** [comment]
This is done, but I should check if there can be also a transition animation.

**Comment by DianaTavares** [comment]
Love it!!
And the zoom was suggested in all interviews, and we didn't have target orbit. Then it is a need feature. 

I like the transition between zooms but if it is not a lot of time-consuming, then implement the animation, other way, close the issue as done.

**Comment by AgustinVallejo** [comment]
Should be ready to close now.
