### ISSUE TITLE
Small changes that affect all screens 

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/keplers-laws#6]
- [x] Move the time control to the top
- [x] make the pink planet a little bigger to easily identify it
- [x] add cuing arrows in the planet that disappear when the user touches for the first time the planet
- [x] put the Always circular checkbox in the controls panels, in the bottom of the first list of checkboxes. 
Example for intro: 
![image](https://user-images.githubusercontent.com/26031501/229955601-2d6b4563-fc47-4435-aa20-d8fec0c1ca52.png)
 For the second law, put it below periapsis, and for the third law, below the period checkbox. 

- [x] Find a more centered place to put the system in all the initial states of the screens 
- [x] limit the size of the orbits to the play area. No matter that the "escape velocity" is not visible in the simulations. 
- [x] Make c/a in the first screen (eccentricity) to look as a fraction in the eccentricity readout

**Comment by AgustinVallejo** [comment]
From today's meeting (April 5th):

- [ ] Make the 2nd and 3rd laws' panels accordeons.
- [ ] Implement the Area Values number display (Might be temporary)

**Comment by AgustinVallejo** [comment]
Turned the remaining items into issues.
