### ISSUE TITLE
changes in the panel control: icons in third law and dive the panel into two

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/keplers-laws#62]
- [ ] Semimajor Axis (a) and Period (T) need icons, and for that, the panel needs to be a little bigger:

![image](https://github.com/phetsims/keplers-laws/assets/26031501/98f6a1c7-4b22-4ebb-a211-4d575f6cef94)

Add the icons (the one with back strokes is for projector mode)
![Kepler's Laws-31](https://github.com/phetsims/keplers-laws/assets/26031501/a4b98f39-bdeb-4219-ac92-c3603c3c0c73)
![Kepler's Laws-32](https://github.com/phetsims/keplers-laws/assets/26031501/8b73cfbe-0e0f-48f5-b00a-b0e4d3d8cdfc)
![Kepler's Laws-33](https://github.com/phetsims/keplers-laws/assets/26031501/2936a346-5b25-4c51-8bac-d2fe6601f0f7)

and all the panels should have the same size on all screens.

- [x] Divide the panels into two, one for the controls that change on all screens, and the other for the controls that are the same:
![image](https://github.com/phetsims/keplers-laws/assets/26031501/bbfe1086-2a00-4d8d-ba9b-182f161dee19)

**Comment by DianaTavares** [comment]
Also, looks strange that the panels are different size. I think all control panels need to have the same length. 

![image](https://github.com/phetsims/keplers-laws/assets/26031501/e0d5cc7a-0b58-4260-ad50-7f39d52cca95)

**Comment by AgustinVallejo** [comment]
Yes! I'm working on that... It's because I'm trying to set them with a fixed Y position. Should be fixed in the future.

**Comment by AgustinVallejo** [comment]
Hello, the "desired" mechanics is set in place. Please review and let me know if you like how it ended up: The general controls no longer move vertically, instead the top gap is filled depending on the Law. Feels a bit weirds but I'm sure it's more desirable than the general panel jumping around, as it causes visual confusion and a sense that all the right hand is new.

**Comment by DianaTavares** [comment]
and we still need the icons for the third screen: 
![image](https://github.com/phetsims/keplers-laws/assets/26031501/0ab41fb3-80f1-42d8-b772-88eca86fc6f7)

**Comment by DianaTavares** [comment]
Perfect!!!
