### ISSUE TITLE
Correct PDOM order structure

### ISSUE THREAD

**Issue by AgustinVallejo** [phetsims/keplers-laws#64]
@pixelzoom Mentioned that the sim is not currently using the correct pattern for setting up the PDOM order. We'll meet today to sort that out.

Also, remember to:

- [x] Set zoom buttons at the end of the pdom, before reset button.
- [x] Put Law Selection menu just after the play area.

**Comment by pixelzoom** [comment]
From 7/12/23 Slack thread:

@kathy-phet:
@pixelzoom @AgustinVallejo - Chris, you mentioned a couple weeks ago when working a bit on MSS and/or KL, that the alt-input implementation needed some changes to bring it up to the current patterns / approach. Would you have time to connect with @AgustinVallejo  and ideally @jonathanolson to share your experience with alt-input and explain what needs to be done for these sims to bring up the alt-input implementation / documentation from a code perspective?

@pixelzoom:
es, but… Tomorrow is mostly filled with meetings. And I’m out July 14-21.  In the meantime, I’d recommend a close read of https://github.com/phetsims/phet-info/blob/master/doc/alternative-input-quickstart-guide.md.  Especially the bit about setting `pdomOrder` explicitly for ScreenViews — do not rely on the default order that corresponds to the scenegraph structure.

@kathy-phet:
Can you recommend a sim for @AgustinVallejo  to review as an example?

@pixelzoom:
geometric-optics.  Search for “pdomOrder” to see how traversal order is explicitly set for the ScreenView and scenes.  Note the use of screenViewRootNode in GOScreenView, as described in https://github.com/phetsims/phet-info/blob/master/doc/alternative-input-quickstart-guide.md.

fourier-making-waves is another exemplar. Again search for “pdomOrder” and “screenViewRootNode”.
