### ISSUE TITLE
Bar graphs in the Swept Area 

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/keplers-laws#65]
The width of the bars should always be the same in order to compare the area:
![image](https://github.com/phetsims/keplers-laws/assets/26031501/4166f8b3-b536-4c9a-b27e-c772473fba06)
![image](https://github.com/phetsims/keplers-laws/assets/26031501/a4e2242d-3576-49e6-b669-0c63207346ab)

- [x] Leave the small width in all the period divisions to have width consistent. 

- [x] It is strange that the size of the bars don't grow up when the size of the orbit is growing.  That affects the scaling of the graph, and will be necessary to add numbers to the area axes.

**Comment by AgustinVallejo** [comment]
Implemented the numbers feature but might need help from another dev to properly format as we'd like to.
