### ISSUE TITLE
UI sounds are all missing!

### ISSUE THREAD

**Issue by AgustinVallejo** [phetsims/keplers-laws#7]
Probably because of MSS changes, UI sounds are now missing in this sim. Will look into it.

**Comment by samreid** [comment]
I added UI sounds and projector mode. @AgustinVallejo please test/review. Close if ok.

**Comment by AgustinVallejo** [comment]
UI sounds are working! Thanks! Projector mode is still being worked on https://github.com/phetsims/keplers-laws/issues/3 so this issue is good to close
