### ISSUE TITLE
Implement sounds for dotted line warnings: Body will crash into the sun and Body will escape the system

### ISSUE THREAD

**Issue by Ashton-Morris** [phetsims/keplers-laws#70]
I have added these sounds to this [new folder.](https://o365coloradoedu.sharepoint.com/:f:/s/PHYS-phet-pilot/ErAnHyaDl9RNnzKDLx_PcfgB8aEOklPsE-KNSTxUospvpg?e=h5axHc)

- KeplersLaw_BodiesCollide.mp3
- KeplersLaw_ObjectWillEscapetheSystem.mp3

**Comment by AgustinVallejo** [comment]
Seems ok as per sound design meeting.
