### ISSUE TITLE
Add model.md

### ISSUE THREAD

**Issue by AgustinVallejo** [phetsims/keplers-laws#75]

**Comment by pixelzoom** [comment]
For code review #83, I fixed some punctuation in https://github.com/phetsims/keplers-laws/commit/f4a958d45fcc1f2084f537dd1f46908a7445ddae.

**Comment by pixelzoom** [comment]
A few minor fixes in the above commit for #83 Code Review. Otherwise this looks nice.

Reminder that model.md should be reviewed by the designer, to verify that it's appropriate for the audience.

**Comment by DianaTavares** [comment]
Hi! I reviewed the Model.md text and I have these comments: 

1. This text is not clear: 
`The strings are used to show that the planet is always at the same distance from the foci, and that the sum of the distances from the foci to the planet is constant, and it's equal to the major axis.`

I suggest changing it to something like:
`The idea behiand the strings it to build the definition of an ellipse as a set of all points for which the sum of the distances from the two foci remains constant. That constant is two times the major axis value.`

2. Add a word “time intervals” in the text of the second law `The line connecting the Sun to a planet sweeps equal areas in equal times. (1)`

3. It is not the “mean distance”. The text in the third law needs to change to semi-major axis: `The square of the orbital period of a planet is directly proportional to the cube of the semi-major axis of its orbit.`

That are all my comments. Thanks!!
