### ISSUE TITLE
Memory testing

### ISSUE THREAD

**Issue by AgustinVallejo** [phetsims/keplers-laws#77]

**Comment by AgustinVallejo** [comment]
Ran the heap memory testing as indicated, with ~10 minutes intervals between each tests, these are the results:

![image](https://github.com/phetsims/keplers-laws/assets/37052186/5e650f17-754f-40fd-af7b-3fa0c97e4869)

It plateaus at 175MB, so I expect it to be fine.

**Comment by pixelzoom** [comment]
> It plateaus at 175MB, so I expect it to be fine.

That's a red flag for me - much larger than I would expect.  For comparison, Geometric Optics leveled out at ~60MB, see https://github.com/phetsims/geometric-optics/issues/372.  

Were you running a built version, as per the instructions?

**Comment by pixelzoom** [comment]
@AgustinVallejo and I discussed. He thinks it was probably the phetmarks (unbuilt) version.  The process for testing memory is described here: https://github.com/phetsims/QA/blob/main/documentation/qa-book.md#47-memory-leak-testing

**Comment by AgustinVallejo** [comment]
Repeated the test with the built version. It plateaus at 153MB, which is better than the previous test. 

![image](https://github.com/phetsims/keplers-laws/assets/37052186/2872f369-469e-4d22-b91b-fdb514c92975)
