### ISSUE TITLE
credits (will not be completed until after RC testing)

### ISSUE THREAD

**Issue by AgustinVallejo** [phetsims/keplers-laws#80]

**Comment by pixelzoom** [comment]
If you add me... You can add me to "Team" as "Chris Malley (PixelZoom, Inc,)".

**Comment by Nancy-Salpepi** [comment]
QA credits should include Jaron Droder, Clifford Hardin, Nancy Salpepi, Kathryn Woessner

**Comment by pixelzoom** [comment]
> If you add me... You can add me to "Team" as "Chris Malley (PixelZoom, Inc,)".

@AgustinVallejo FYI, I fixed my credits in the above commits, in main and 1.1 branches.

**Comment by Nancy-Salpepi** [comment]
Nothing new to add to QA credits in rc.4

**Comment by KatieWoe** [comment]
I saw Emily Miller was included on old versions of the QA credits, but was removed. We don't normally remove people, can you explain?

**Comment by AgustinVallejo** [comment]
Yup, the credits were copy-pasted from My Solar System but hadn't really been intentionally written. So some of the people that showed up in there were actually related to MSS and not Kepler's.
