### ISSUE TITLE
Does this sim use WebGL?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/keplers-laws#85]
For code review #83 ...

>  - [ ] If the sim uses WebGL, does it have a fallback? Does the fallback perform reasonably well? (run with query parameter `webgl=false`)

I can't tell if this sim uses WebGL. Does it?  I don't see any performance difference with `webgl=false`.

**Comment by AgustinVallejo** [comment]
It doesn't use WebGL. Closing.
