### ISSUE TITLE
Dynamic layout problems with Third Law panels

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/keplers-laws#86]
Noticed during code review #83 ... 

In the Third Law screen, the panels on the left side of the screen resize, sometime drastically, when playing with the sim.

For example, when going from this state:

<img width="1117" alt="screenshot_2708" src="https://github.com/phetsims/keplers-laws/assets/3046552/1cf06a1d-5315-4682-933f-53a0875902f6">

... to this state:

<img width="1120" alt="screenshot_2709" src="https://github.com/phetsims/keplers-laws/assets/3046552/a51ee042-1043-484a-8d49-a9f4ad43444c">

... the width of the panels changes.  

I also see less drastic changes (small changes in width) as the values of T and a change.

This is distracting, and not typical of PhET sims. Unless there's a pedagogical reason for this (which I doubt) it should be fixed.

**Comment by AgustinVallejo** [comment]
Agree, it should be fixed. I'd appreciate some help fixing this.

**Comment by AgustinVallejo** [comment]
Adding to the meta issue of Dynamic Layout: #122

**Comment by pixelzoom** [comment]
To dynamically size the fraction lines that appear in the equation, factor out a FractionNode class, something like this: 

```ts
const FRACTION_LINE_MARGIN = 5;

class FractionNode extends VBox {

    const numeratorNode = new RichText( ThirdLawTextUtils.createPowerStringProperty( KeplersLawsStrings.symbols.periodStringProperty, model.selectedPeriodPowerProperty, new TinyProperty<boolean>( true ) ), KeplersLawsConstants.TEXT_OPTIONS );

    const denominatorNode = new RichText( ThirdLawTextUtils.createPowerStringProperty( KeplersLawsStrings.symbols.semiMajorAxisStringProperty, model.selectedAxisPowerProperty, new TinyProperty<boolean>( true ) ), KeplersLawsConstants.TEXT_OPTIONS );

    const fractionLine = new Line( 0, 0, 1, 0, { stroke: SolarSystemCommonColors.foregroundProperty, lineWidth: 1.5, lineCap: 'round' } );

    // Dynamically size the fraction line.
    Multilink.multilink( [ numeratorNode.boundsProperty, denominatorNode.boundsProperty ],
      ( numeratorBounds, denominatorBounds ) => {
        fractionLine.setLine( 0, 0, Math.max( numeratorBounds.width, denominatorBounds.width ) + FRACTION_LINE_MARGIN, 0 );
      } );

  super( ... );
}
```

**Comment by pixelzoom** [comment]
@pixelzoom I'll take a look at the resizing of this panel.

**Comment by pixelzoom** [comment]
We decided to address maxWidth problems with things inside this panel before addressing the panel behavior.  @AgustinVallejo circle back to me when that has been done.

**Comment by pixelzoom** [comment]
In the above commits, I added maxWidth for symbols and units that appear in fractions (T, a, years, AU).

I see at least one remaining layout problem. As strings change, the fraction lines lose their horizontal alignment. For example, here's what it looks like originally:

<img width="272" alt="screenshot_2751" src="https://github.com/phetsims/keplers-laws/assets/3046552/06bc70da-5e84-4937-969e-f4bc3573f9ca">

And here's what it looks like after pressing the left arrow key once with `?stringTest=dynamic`.  The fraction lines for the units are higher than the others.

<img width="302" alt="screenshot_2750" src="https://github.com/phetsims/keplers-laws/assets/3046552/333f0ba8-534b-4acc-9f04-d9f55396302b">

**Comment by pixelzoom** [comment]
In the above commits, I added maxWidth for symbols and units that appear in fractions (T, a, years, AU).

I see at least one remaining layout problem. As strings change, the fraction lines lose their horizontal alignment. For example, here's what it looks like originally:

<img width="272" alt="screenshot_2751" src="https://github.com/phetsims/keplers-laws/assets/3046552/06bc70da-5e84-4937-969e-f4bc3573f9ca">

And here's what it looks like after pressing the left arrow key once with `?stringTest=dynamic`.  The fraction lines for the units are higher than the others.

<img width="302" alt="screenshot_2750" src="https://github.com/phetsims/keplers-laws/assets/3046552/333f0ba8-534b-4acc-9f04-d9f55396302b">

**Comment by pixelzoom** [comment]
I've been having a lot of difficulty navigating ThirdLawAccordionBox, due to the overuse of nesting that I mentioned in https://github.com/phetsims/keplers-laws/issues/112.  So in the above commit, I reorganized ThirdLawAccordionBox, for 2 reasons: to make my life easier in working on this issue, and to demonstrate the advantages (including for PhET-iO) of organizing things a different way. @AgustinVallejo  Let's discuss https://github.com/phetsims/keplers-laws/commit/3a5b0e74b30cda74b1a8d65afbc731b628d40908 after you've had a chance to review.

**Comment by pixelzoom** [comment]
@AgustinVallejo and I reviewed ThirdLawAccordionBox, and discussed pros and cons of nesting, advantages of factoring out `const` for things that will have a tandem, etc.
