### ISSUE TITLE
Revise string keys

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/keplers-laws#89]
For code review #83 ...

> Make sure the string keys are all perfect. They are difficult to change after 1.0.0 is published. They should be literal, they should be explicit, and they should be consistent. This will also be the PhET-iO phetioID name in Studio etc. Guidelines for string keys are:
> 
> (1) Strings keys should generally match their values. E.g.:

There are many string keys that do not match their values, eg `"circularOrbit"` => "Always circular".  And there is some undesirable nesting of keys, like `"graph.a"`. These should be changed, because it will make strings difficult to find in Studio when this sim is instrumented for PhET-iO.

This patch show keys that are more appropriate, and compatible with PhET-iO:

<details>
<summary>patch</summary>

```diff
Subject: [PATCH] minor fixes, https://github.com/phetsims/keplers-laws/issues/76
---
Index: keplers-laws-strings_en.json
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/keplers-laws-strings_en.json b/keplers-laws-strings_en.json
--- a/keplers-laws-strings_en.json	(revision e7fbab5d7f0f33dda454482ecf33d6ba78d3536a)
+++ b/keplers-laws-strings_en.json	(date 1692189036725)
@@ -32,16 +32,16 @@
   "foci": {
     "value": "Foci"
   },
-  "strings": {
+  "string": {
     "value": "String"
   },
-  "semiaxis": {
+  "semiaxes": {
     "value": "Semiaxes"
   },
   "eccentricity": {
     "value": "Eccentricity"
   },
-  "eccentricityEquation": {
+  "eccentricityEquals": {
     "value": "Eccentricity ="
   },
   "apoapsis": {
@@ -62,16 +62,16 @@
   "eraser": {
     "value": "Eraser"
   },
-  "area.periodDivision": {
+  "periodDivisions": {
     "value": "Period Divisions"
   },
-  "area.values": {
+  "areaValues": {
     "value": "Area Values"
   },
-  "area.timeValues": {
+  "timeValues": {
     "value": "Time Values"
   },
-  "area.areaUnits": {
+  "areaUnits": {
     "value": "Area (AU<sup>2</sup>)"
   },
   "sweptArea": {
@@ -83,70 +83,70 @@
   "graph.title": {
     "value": "T{{periodPower}} vs a{{axisPower}} Graph"
   },
-  "graph.a": {
+  "semimajorAxisa": {
     "value": "Semimajor Axis (a)"
   },
-  "graph.t": {
+  "PeriodT": {
     "value": "Period (T)"
   },
-  "units.AU": {
+  "AU": {
     "value": "AU"
   },
-  "units.AU2": {
+  "AU2": {
     "value": "AU²"
   },
-  "units.years": {
+  "years": {
     "value": "years"
   },
-  "units.kms": {
+  "kmPerS": {
     "value": "km/s"
   },
-  "units.degrees": {
+  "degrees": {
     "value": "°"
   },
-  "symbols.semiMajorAxis": {
+  "a": {
     "value": "a"
   },
-  "symbols.semiMajorAxisSquared": {
+  "a2": {
     "value": "a<sup>2</sup>"
   },
-  "symbols.semiMajorAxisCubed": {
+  "a3": {
     "value": "a<sup>3</sup>"
   },
-  "symbols.semiMinorAxis": {
+  "b": {
     "value": "b"
   },
-  "symbols.focalDistance": {
+  "c": {
     "value": "c"
   },
-  "symbols.period": {
+  "T": {
     "value": "T"
   },
-  "symbols.periodSquared": {
+  "T2": {
     "value": "T<sup>2</sup>"
   },
-  "symbols.periodCubed": {
+  "T3": {
     "value": "T<sup>3</sup>"
   },
-  "symbols.radius": {
+  "R": {
     "value": "R"
   },
-  "symbols.positionMagnitude": {
+  "rAbsoluteValue": {
     "value": "|r|"
   },
-  "symbols.velocityMagnitude": {
+  "vAbsoluteValue": {
     "value": "|v|"
   },
-  "symbols.distance1": {
+  "d1": {
     "value": "d<sub>1</sub>"
   },
-  "symbols.distance2": {
+  "d2": {
     "value": "d<sub>2</sub>"
   },
-  "symbols.distanceAngle": {
+  "0r": {
     "value": "θ<sub>r</sub>"
   },
-  "symbols.velocityAngle": {
+  "0v": {
     "value": "θ<sub>v</sub>"
   },
   "pattern.textEqualsValueUnits": {
@@ -155,37 +155,37 @@
   "pattern.valueUnits": {
     "value": "{{value}} {{units}}"
   },
-  "warning.warning": {
+  "pattern.warningMessage": {
     "value": "Warning: {{message}}"
   },
-  "warning.crashOrbit": {
+  "theBodyWillCrashIntoTheSun": {
     "value": "The body will crash into the sun"
   },
-  "warning.escapeOrbit": {
+  "theBodyWillEscapeTheSystem": {
     "value": "The body will escape the system"
   },
-  "orbit.mercury": {
+  "mercury": {
     "value": "Mercury"
   },
-  "orbit.venus": {
+  "venus": {
     "value": "Venus"
   },
-  "orbit.earth": {
+  "earth": {
     "value": "Earth"
   },
-  "orbit.mars": {
+  "mars": {
     "value": "Mars"
   },
-  "orbit.jupiter": {
+  "jupiter": {
     "value": "Jupiter"
   },
-  "orbit.eris": {
+  "eris": {
     "value": "Eris"
   },
-  "orbit.nereid": {
+  "nereid": {
     "value": "Nereid"
   },
-  "orbit.halley": {
+  "halley": {
     "value": "Halley"
   },
   "infoDialog.semimajorAxis": {
```

</details>

You might also want to consult with @arouinfar on this, because she has a lot of experience with string keys that are appropriate for PhET-iO.

**Comment by pixelzoom** [comment]
I don't know what the status of the 1.0 version is -- are there translations? Can we break them?    It's going to be really unfortunate if we can't change these string keys.

**Comment by AgustinVallejo** [comment]
1.0 Was published for showcasing in Toronto, but it hasn't been published on the website so no translations yet.

**Comment by pixelzoom** [comment]
So it sounds like string keys can be changed without worrying about previous versions.

@AgustinVallejo I see that you assigned me. What would you like me to do for this issue?

**Comment by pixelzoom** [comment]
I checked with @jbphet about how to proceed here.  

We looked in babel, and there 42 translation files.  All of those files contain a translation for `"screen.lab"`, and nothing else.  It looks like there was a "Lab" screen in 1.0, but it has been renamed "All Laws".  But we are not clear why only `"screen.lab"` appears in all of these files.   @jbphet recommended that we delete all files under babel/keplers-laws/ before publishing, unless there's some reason that we don't know about for keeping them.  @AgustinVallejo please comment and handle this aspect of this issue.

Since none of the keys in keplers-laws-strings_en.json appear in the babel files, @jbphet said it's safe to change them.  So I'll proceed with that.

**Comment by pixelzoom** [comment]
I got a good start on renames in the above commits.  I'll continue next Tuesday. And I have a list of questions to discuss with @AgustinVallejo.

**Comment by pixelzoom** [comment]
This string:

```
  "units.AU2": {
    "value": "AU<sup>2</sup>"
  },
```

... is currently showing up as:

<img width="1145" alt="screenshot_2762" src="https://github.com/phetsims/keplers-laws/assets/3046552/c59a10e9-e159-4763-a44e-b8d881ec6a20">

Do we want to add a string for "AU<sup>3</sup>"?  Or do we want to derive  "AU<sup>2</sup>" and  "AU<sup>3</sup>" from  "units.AU"?

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/keplers-laws/commit/6c86b5a867ac374b097b803eabdb0d7909a9e781, I fixed the problem with rendering A<sup>2</sup>, see screenshot below.

<img width="1142" alt="screenshot_2763" src="https://github.com/phetsims/keplers-laws/assets/3046552/64d4d1cb-0a16-4a37-86fb-e1c6901256b9">

**Comment by pixelzoom** [comment]
The 4 commits directly above deal with standardizing on the terminology "Orbital Data" and "More Orbital Data", based on the "More Orbital Data" control in Simulation Preferences.

**Comment by pixelzoom** [comment]
The 6 commits directly above deal with standardizing on the terminology "Orbital Data" and "More Orbital Data", based on the "More Orbital Data" control in Simulation Preferences.

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/keplers-laws/issues/89#issuecomment-1707003922, I said:

> Do we want to add a string for "AU<sup>3</sup>"?  Or do we want to derive  "AU<sup>2</sup>" and  "AU<sup>3</sup>" from  "units.AU"?   It probably depends on RTL languages.  Please check with @DianaTavares or @arouinfar.

This is the last remaining issues for string keys.  My feeling is that strings involving `<sup>`, `<sub>`, and `| |` should be derived, not included in strings.json   And this sim is inconsistent about whether such strings are in strings.json or derived -- for example, `AU<sup>3</sub>` is in strings.json, while `AU<sup>2</sub>` is derived.   

The strings that I feel should be derived are:

```ts
  "units.AU2": {
    "value": "AU<sup>2</sup>"
  },
  "symbol.a2": {
    "value": "a<sup>2</sup>"
  },
  "symbol.a3": {
    "value": "a<sup>3</sup>"
  },
  "symbol.T2": {
    "value": "T<sup>2</sup>"
  },
  "symbol.T3": {
    "value": "T<sup>3</sup>"
  },
  "symbol.positionMagnitude": {
    "value": "|r|"
  },
  "symbol.velocityMagnitude": {
    "value": "|v|"
  },
  "symbol.d1": {
    "value": "d<sub>1</sub>"
  },
  "symbol.d2": {
    "value": "d<sub>2</sub>"
  },
  "symbol.distanceAngle": {
    "value": "θ<sub>r</sub>"
  },
  "symbol.velocityAngle": {
    "value": "θ<sub>v</sub>"
  },
  "symbol.rvAngle": {
    "value": "θ<sub>rv</sub>"
  },
```

**Comment by arouinfar** [comment]
>  My feeling is that strings involving `<sup>`, `<sub>`, and `| |` should be derived, not included in strings.json.   

I agree, it makes sense to derive these strings. 

> It probably depends on RTL languages.  Please check with @DianaTavares or @arouinfar.

Numbers are written left-to-right in RTL languages (e.g. one hundred is written 1-0-0 not 0-0-1), and it's my understanding that exponents are treated in the same way. Exponents appear in the upper right corner of the base number, so I'm not sure if we even need a pattern string to handle  AU<sup>2</sup> vs. <sup>2</sup>AU.

**Comment by pixelzoom** [comment]
Thanks @arouinfar.

In the above commits, I moved several strings out of strings.json, and derived them in KeplersLawDerivedStrings.ts

**Comment by pixelzoom** [comment]
I believe that this work is done.   There are a still a few places where symbols are duplicated in descriptions that appear in Info dialogs, but I think that's OK, and probably easier to translate.  For example:

```ts
  "infoDialog.planetsPositionVector": {
    "value": "<b>Planet's position vector (|r| and θ<sub>r</sub>):</b> the vector magnitude |r| is equal to the distance between the star and the planet. The vector direction (θ<sub>r</sub>) is measured with respect to the horizontal."
  },
```

@AgustinVallejo please review. Close if OK.

**Comment by pixelzoom** [comment]
@AgustinVallejo also note that I deleted all existing translation files in https://github.com/phetsims/babel/commit/6afb446fad1b8f84709c593744e43292c47be96a, as recommended in https://github.com/phetsims/keplers-laws/issues/89#issuecomment-1703374741.
