### ISSUE TITLE
Turn on "todo-should-have-issue" lint rule

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/keplers-laws#95]
For code review #83 ...

> - [ ] Are there any TODO or FIXME or REVIEW comments in the code? They should be addressed or promoted to GitHub issues.

This override needs to be removed from package.json in keplers-laws, solar-system-common, and my-solar-system:

```ts
    "rules": {
      "todo-should-have-issue": "off"
    },
```

... and any `TODO` comments will need to include a URL for a GitHub issue.

**Comment by AgustinVallejo** [comment]
Removed. Two questions:
1. Should they also be taken out of files such as solar-system-common-tests.json or my-solar-system_en.html or are they auto generated from the package.json of each repo?
2. Should something be done about My Solar System afterwards? Like redeploying?

**Comment by AgustinVallejo** [comment]
Understood, thanks! Then this seems good for closing
