### ISSUE TITLE
Dynamic layout problem with Foci display

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/keplers-laws#98]
For code review #83 ...

Testing with `?stringTest=dynamic`, I see this layout problem in the First Law screen when the "Foci" and "String" checkboxes are checked:

<img width="449" alt="screenshot_2713" src="https://github.com/phetsims/keplers-laws/assets/3046552/049abfd8-161e-48e0-b280-8ab546dd40c1">

**Comment by pixelzoom** [comment]
Even worse with `?stringTest=long`:

<img width="707" alt="screenshot_2718" src="https://github.com/phetsims/keplers-laws/assets/3046552/bad5f4be-4081-43b4-8751-3ed2d1c5fa61">

**Comment by AgustinVallejo** [comment]
Adding to the meta issue of Dynamic Layout: #122

**Comment by pixelzoom** [comment]
I'll do this one.

**Comment by pixelzoom** [comment]
Ready for review by @AgustinVallejo.   Let me know if you have questions. Close if OK.

The first thing you'll notice is that DistancesDisplayNode looks very different.  The problem with the layout was an inappropriate use of VBox to combine each label + arrow.   There's some duplication here, unless we want to change the `updateDisplay` listener function, I think we should live with it. 

Note that I also changed how the display switches between d1/d2 and R, using a DerivedProperty. See https://github.com/phetsims/keplers-laws/commit/7dc60f24ffa4cf50da6a786df1650d3623a39597
