### ISSUE TITLE
Dynamic layout problem with axis labels in ThirdLawGraph

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/keplers-laws#99]
For code review #83 ...

When running with `?stringTest=dynamic`, this axis labels are not positioned correctly. 'a' does not stay horizontally centered on the x-axis, and 'T' overlaps the y-axis.

<img width="353" alt="screenshot_2717" src="https://github.com/phetsims/keplers-laws/assets/3046552/160e54de-69a9-4df6-8f13-d6a014ca96f9">

**Comment by AgustinVallejo** [comment]
Adding to the meta issue of Dynamic Layout: #122

**Comment by pixelzoom** [comment]
I'll look at the one.

**Comment by pixelzoom** [comment]
Fixed in the above commits. @AgustinVallejo please review, close if OK.
